import React, { useState, useEffect, useRef, useMemo } from "react";
import {
  CloudRain,
  AlertTriangle,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Info,
  Compass,
  Maximize2,
  Layers,
  MapPin,
  TrendingUp,
  ShieldAlert,
  Smartphone,
  Download,
  FileText,
  Map as MapIcon,
  X
} from "lucide-react";

const WeatherAdvisory = () => {
  const [geoData, setGeoData] = useState(null);
  const [advisoryData, setAdvisoryData] = useState(null);
  const [selectedDay, setSelectedDay] = useState(1);
  const [selectedMode, setSelectedMode] = useState("forecast"); // 'forecast' or 'realtime'
  const [activeHazard, setActiveHazard] = useState("Rainfall"); // 'Rainfall' or 'Wind'
  const [realtimeData, setRealtimeData] = useState(null);
  const [selectedRealtimeFrameIdx, setSelectedRealtimeFrameIdx] = useState(0);
  const [activeRegion, setActiveRegion] = useState("All");
  const [hoveredProvince, setHoveredProvince] = useState(null);
  const [selectedProvince, setSelectedProvince] = useState(null);
  const [tooltipPos, setTooltipPos] = useState({ x: 0, y: 0 });
  const [isTooltipVisible, setIsTooltipVisible] = useState(false);
  const [showLabels, setShowLabels] = useState(false);
  const [activeTab, setActiveTab] = useState("map"); // 'map' or 'bulletin' on mobile
  const mapContainerRef = useRef(null);

  useEffect(() => {
    // Fetch GeoJSON map of provinces (178 KB minimal file)
    fetch("/data/ph_provinces.json")
      .then((res) => {
        if (!res.ok) throw new Error("Network response was not ok");
        return res.json();
      })
      .then((data) => setGeoData(data))
      .catch((err) => console.error("Failed to load provinces map:", err));

    // Fetch advisory rainfall data generated by generate_advisory_data.py
    fetch("/data/advisory_data.json")
      .then((res) => {
        if (!res.ok) throw new Error("Network response was not ok");
        return res.json();
      })
      .then((data) => setAdvisoryData(data))
      .catch((err) => console.error("Failed to load advisory data:", err));

    const fetchJaxaData = () => {
      // Fetch real-time JAXA GSMaP precipitation data
      fetch("/api/fetch-gsmap")
        .then((res) => res.json())
        .then((data) => {
          if (data.success) {
            setRealtimeData(data);
          }
        })
        .catch((err) => console.warn("Failed to fetch real-time GSMaP data:", err));
    };

    // Initial fetch
    fetchJaxaData();

    // Auto-refresh ONLY JAXA GSMaP data every 10 minutes (600000 ms)
    const intervalId = setInterval(fetchJaxaData, 600000);

    return () => clearInterval(intervalId);
  }, []);

  const currentDayData = useMemo(() => {
    if (selectedMode === "realtime") {
      const selectedFrame = realtimeData?.frames?.[selectedRealtimeFrameIdx];
      const gsmapProvinces = selectedFrame?.provinces || realtimeData?.provinces || {};
      const realtimeProvinces = {};

      Object.entries(gsmapProvinces).forEach(([prov, info]) => {
        const rawRain = info.rainfall !== undefined ? info.rainfall : (info.rainfall_mm || 0);
        realtimeProvinces[prov] = {
          ...info,
          rainfall: rawRain,
          rainfall_mm: rawRain
        };
      });

      return {
        validity: `JAXA GSMaP Observed (${selectedFrame?.formattedTime || "Live Satellite"})`,
        provinces: realtimeProvinces
      };
    }

    if (!advisoryData) return null;
    if (advisoryData.days && advisoryData.days[selectedDay]) {
      return advisoryData.days[selectedDay];
    }
    return {
      validity: advisoryData.validity || "",
      provinces: advisoryData.provinces || {}
    };
  }, [advisoryData, selectedDay, selectedMode, realtimeData, selectedRealtimeFrameIdx]);

  const getIslandGroup = (region) => {
    if (!region) return "Luzon";
    const r = region.toLowerCase();
    if (r.includes("visayas")) return "Visayas";
    if (
      r.includes("zamboanga") ||
      r.includes("mindanao") ||
      r.includes("davao") ||
      r.includes("soccsksargen") ||
      r.includes("caraga") ||
      r.includes("bangsamoro") ||
      r.includes("muslim")
    ) {
      return "Mindanao";
    }
    return "Luzon";
  };

  // ── CORE SVG PROJECTION & BOUNDS MAPPING ──
  const mapData = useMemo(() => {
    if (!geoData) return null;

    let minLon = 180, maxLon = -180;
    let minLat = 90, maxLat = -90;

    // Scan coordinates to find strict bounding box limits
    const findBounds = (c) => {
      if (typeof c[0] === 'number') {
        const [lon, lat] = c;
        if (lon < minLon) minLon = lon;
        if (lon > maxLon) maxLon = lon;
        if (lat < minLat) minLat = lat;
        if (lat > maxLat) maxLat = lat;
      } else {
        c.forEach(findBounds);
      }
    };

    geoData.features.forEach((f) => {
      findBounds(f.geometry.coordinates);
    });

    // High-resolution tall aspect ratio canvas
    const canvasWidth = 1000;
    const canvasHeight = 1400;

    // Standard Equirectangular projection mapping to SVG space
    const project = (lon, lat) => {
      const x = ((lon - minLon) / (maxLon - minLon)) * canvasWidth;
      const y = ((maxLat - lat) / (maxLat - minLat)) * canvasHeight;
      return [x, y];
    };

    // Projected feature shapes and centroids
    const projectedFeatures = geoData.features.map((f) => {
      const provName = f.properties.PROV_NAME || f.properties.PROVINCE || f.properties.NAME_1 || f.properties.name || "Unknown";
      const region = f.properties.REGION || "";
      const group = getIslandGroup(region);

      // Recursive path string generator (Polygon / MultiPolygon)
      const generateD = (coords, type) => {
        if (type === "Polygon") {
          return coords.map(ring => {
            return ring.map((coord, index) => {
              const [x, y] = project(coord[0], coord[1]);
              return `${index === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
            }).join(' ') + ' Z';
          }).join(' ');
        } else if (type === "MultiPolygon") {
          return coords.map(poly => {
            return poly.map(ring => {
              return ring.map((coord, index) => {
                const [x, y] = project(coord[0], coord[1]);
                return `${index === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
              }).join(' ') + ' Z';
            }).join(' ');
          }).join(' ');
        }
        return "";
      };

      const d = generateD(f.geometry.coordinates, f.geometry.type);

      // Centroid (average coordinate position)
      let sumX = 0, sumY = 0, count = 0;
      const getCentroid = (c) => {
        if (typeof c[0] === 'number') {
          const [lon, lat] = c;
          const [x, y] = project(lon, lat);
          sumX += x;
          sumY += y;
          count++;
        } else {
          c.forEach(getCentroid);
        }
      };
      getCentroid(f.geometry.coordinates);

      return {
        id: f.properties.ID_1 || provName,
        name: provName,
        region,
        group,
        d,
        centroid: count > 0 ? [sumX / count, sumY / count] : [canvasWidth / 2, canvasHeight / 2]
      };
    });

    // Regional coordinate bounds in SVG canvas space
    const bounds = {
      All: { minX: 0, maxX: 1000, minY: 0, maxY: canvasHeight },
      Luzon: { minX: canvasWidth, maxX: 0, minY: canvasHeight, maxY: 0 },
      Visayas: { minX: canvasWidth, maxX: 0, minY: canvasHeight, maxY: 0 },
      Mindanao: { minX: canvasWidth, maxX: 0, minY: canvasHeight, maxY: 0 }
    };

    // Calculate strict bounding box enclosing each island group
    projectedFeatures.forEach((f) => {
      const g = f.group;
      const originalFeature = geoData.features.find(
        (orig) =>
          (orig.properties.ID_1 || orig.properties.PROV_NAME || orig.properties.PROVINCE || orig.properties.NAME_1) === f.id ||
          orig.properties.PROV_NAME === f.name
      );

      if (originalFeature) {
        const updateBounds = (c) => {
          if (typeof c[0] === 'number') {
            const [lon, lat] = c;
            const [x, y] = project(lon, lat);
            if (x < bounds[g].minX) bounds[g].minX = x;
            if (x > bounds[g].maxX) bounds[g].maxX = x;
            if (y < bounds[g].minY) bounds[g].minY = y;
            if (y > bounds[g].maxY) bounds[g].maxY = y;
          } else {
            c.forEach(updateBounds);
          }
        };
        updateBounds(originalFeature.geometry.coordinates);
      }
    });

    // Apply padding of 8% to prevent clipping at the borders of zoomed regions
    Object.keys(bounds).forEach((key) => {
      if (key === "All") return;
      const b = bounds[key];
      const w = b.maxX - b.minX;
      const h = b.maxY - b.minY;
      const padX = w * 0.08;
      const padY = h * 0.08;

      bounds[key] = {
        minX: Math.max(0, b.minX - padX),
        maxX: Math.min(canvasWidth, b.maxX + padX),
        minY: Math.max(0, b.minY - padY),
        maxY: Math.min(canvasHeight, b.maxY + padY)
      };
    });

    // Extract overlay paths for Laguna de Bay, Taal Lake, and Taal Volcano to mask colors
    const batangasFeature = geoData.features.find(f => {
      const name = f.properties.PROV_NAME || f.properties.PROVINCE || f.properties.NAME_1 || f.properties.name || "";
      return name === "Batangas";
    });
    const lagunaFeature = geoData.features.find(f => {
      const name = f.properties.PROV_NAME || f.properties.PROVINCE || f.properties.NAME_1 || f.properties.name || "";
      return name === "Laguna";
    });

    const projectRing = (ring) => {
      return ring.map((coord, index) => {
        const [x, y] = project(coord[0], coord[1]);
        return `${index === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
      }).join(' ') + ' Z';
    };

    let taalLakePath = "";
    let taalVolcanoPath = "";
    if (batangasFeature && batangasFeature.geometry.type === "MultiPolygon") {
      const coords = batangasFeature.geometry.coordinates;
      if (coords[2] && coords[2][1]) {
        taalLakePath = projectRing(coords[2][1]);
      }
      if (coords[3] && coords[3][0]) {
        taalVolcanoPath = projectRing(coords[3][0]);
      }
    }

    let lagunaDeBayPath = "";
    if (lagunaFeature && lagunaFeature.geometry.type === "Polygon") {
      const coords = lagunaFeature.geometry.coordinates;
      if (coords[2]) {
        lagunaDeBayPath = projectRing(coords[2]);
      }
    }

    return {
      features: projectedFeatures,
      bounds,
      canvasWidth,
      canvasHeight,
      lagunaDeBayPath,
      taalLakePath,
      taalVolcanoPath
    };
  }, [geoData]);

  // Compute active viewBox with coordinates based on zoom selection
  const activeViewBox = useMemo(() => {
    if (!mapData) return "0 0 1000 1400";
    const b = mapData.bounds[activeRegion];
    if (!b) return "0 0 1000 1400";
    const w = b.maxX - b.minX;
    const h = b.maxY - b.minY;
    return `${b.minX.toFixed(1)} ${b.minY.toFixed(1)} ${w.toFixed(1)} ${h.toFixed(1)}`;
  }, [mapData, activeRegion]);

  

  
  
  const getWindCategory = (kph) => {
    const rounded = Math.round(kph);
    if (rounded >= 118) return "red";
    if (rounded >= 89) return "orange";
    if (rounded >= 62) return "yellow";
    if (rounded >= 39) return "lightBlue";
    return "normal";
  };

  const getCategory = (mm) => {
    if (selectedMode === "realtime") {
      if (mm >= 30) return "red";
      if (mm >= 15) return "orange";
      if (mm >= 7.5) return "yellow";
      if (mm >= 2.5) return "lightBlue";
      return "normal";
    }
    const roundedMm = Math.round(mm);
    if (roundedMm >= 200) return "red";
    if (roundedMm >= 100) return "orange";
    if (roundedMm >= 50) return "yellow";
    if (roundedMm >= 25) return "lightBlue";
    return "normal";
  };

  // Warning metrics summary
  const warningMetrics = useMemo(() => {
    if (!currentDayData || !currentDayData.provinces) return { red: 0, orange: 0, yellow: 0, lightBlue: 0, normal: 0 };
    let red = 0, orange = 0, yellow = 0, lightBlue = 0, normal = 0;
    Object.values(currentDayData.provinces).forEach((p) => {
      const val = activeHazard === "Wind" ? (p.wind_kph || 0) : (p.rainfall !== undefined ? p.rainfall : (p.rainfall_mm || 0));
      const cat = activeHazard === "Wind" ? getWindCategory(val) : getCategory(val);
      if (cat === "red") red++;
      else if (cat === "orange") orange++;
      else if (cat === "yellow") yellow++;
      else if (cat === "lightBlue") lightBlue++;
      else normal++;
    });
    return { red, orange, yellow, lightBlue, normal };
  }, [currentDayData]);

  // Warning provinces lists
  const warningProvinces = useMemo(() => {
    const red = [];
    const orange = [];
    const yellow = [];
    const lightBlue = [];

    if (currentDayData && currentDayData.provinces) {
      Object.entries(currentDayData.provinces).forEach(([name, p]) => {
        const val = activeHazard === "Wind" ? (p.wind_kph || 0) : (p.rainfall !== undefined ? p.rainfall : (p.rainfall_mm || 0));
        const cat = activeHazard === "Wind" ? getWindCategory(val) : getCategory(val);
        if (cat === "red") red.push(name);
        else if (cat === "orange") orange.push(name);
        else if (cat === "yellow") yellow.push(name);
        else if (cat === "lightBlue") lightBlue.push(name);
      });
      red.sort();
      orange.sort();
      yellow.sort();
      lightBlue.sort();
    }

    return { red, orange, yellow, lightBlue };
  }, [currentDayData]);


  const getHazardColor = (val) => {
    const cat = activeHazard === "Wind" ? getWindCategory(val) : getCategory(val);
    if (cat === "red") return "#DC2626";
    if (cat === "orange") return "#F97316";
    if (cat === "yellow") return "#EAB308";
    if (cat === "lightBlue") return "#38BDF8";
    return "#334155";
  };


    const getAlertLevel = (val) => {
    const cat = activeHazard === "Wind" ? getWindCategory(val) : getCategory(val);
    
    if (activeHazard === "Wind") {
        if (cat === "red") return { title: "TYPHOON ALERT", style: "bg-red-500/10 text-red-400 border-red-500/25", text: "Extreme damage to structures expected. Evacuate if necessary." };
        if (cat === "orange") return { title: "SEVERE TS ALERT", style: "bg-orange-500/10 text-orange-400 border-orange-500/25", text: "Significant wind damage possible. Secure loose objects." };
        if (cat === "yellow") return { title: "TROPICAL STORM", style: "bg-yellow-500/10 text-yellow-400 border-yellow-500/25", text: "Moderate wind threat. Monitor updates closely." };
        if (cat === "lightBlue") return { title: "DEPRESSION ALERT", style: "bg-sky-500/10 text-sky-400 border-sky-500/25", text: "Breezy conditions. Minor wind impacts possible." };
        return { title: "NO WARNING", style: "bg-slate-900/60 text-slate-400 border-slate-800/40", text: "Standard conditions." };
    }

    if (selectedMode === "realtime") {
      if (cat === "red") return { title: "Torrential Rain", style: "bg-red-500/10 text-red-400 border-red-500/25", text: "Severe torrential rainfall observed (>30 mm/hr)." };
      if (cat === "orange") return { title: "Heavy Rain", style: "bg-orange-500/10 text-orange-400 border-orange-500/25", text: "Heavy rainfall observed (15-30 mm/hr)." };
      if (cat === "yellow") return { title: "Moderate Rain", style: "bg-yellow-500/10 text-yellow-400 border-yellow-500/25", text: "Moderate rainfall observed (7.5-15 mm/hr)." };
      if (cat === "lightBlue") return { title: "Light Rain", style: "bg-sky-500/10 text-sky-400 border-sky-500/25", text: "Light rainfall observed (2.5-7.5 mm/hr)." };
      return { title: "Clear / Trace", style: "bg-slate-900/60 text-slate-400 border-slate-800/40", text: "No significant rainfall currently." };
    }
    if (cat === "red") return { title: "Severe Red Warning", style: "bg-red-500/10 text-red-400 border-red-500/25", text: "Severe flooding and widespread landslides are expected. Move to safe high grounds immediately." };
    if (cat === "orange") return { title: "Heavy Orange Alert", style: "bg-orange-500/10 text-orange-400 border-orange-500/25", text: "Flooding is highly likely. Residents near rivers and hills should prepare to evacuate." };
    if (cat === "yellow") return { title: "Moderate Yellow Advisory", style: "bg-yellow-500/10 text-yellow-400 border-yellow-500/25", text: "Localized minor flooding is possible in low-lying and urban areas." };
    if (cat === "lightBlue") return { title: "Light Blue Alert", style: "bg-sky-500/10 text-sky-400 border-sky-500/25", text: "Localized minor ponding and wet roads possible. Exercise standard caution." };
    return { title: "No Warnings Active", style: "bg-slate-900/60 text-slate-400 border-slate-800/40", text: "Standard background levels. Scattered light rains possible." };
  };

  const handleMouseMove = (e) => {
    if (mapContainerRef.current) {
      const rect = mapContainerRef.current.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;

      // Tooltip dimensions: width is 290px, height is 210px
      const tooltipWidth = 290;
      const tooltipHeight = 210;

      let finalX = x + 15;
      let finalY = y + 15;

      // Check right boundary collision
      if (x + tooltipWidth > rect.width) {
        finalX = x - tooltipWidth - 15;
      }

      // Check bottom boundary collision
      if (y + tooltipHeight > rect.height) {
        finalY = y - tooltipHeight - 15;
      }

      // Keep within bounds
      finalX = Math.max(10, finalX);
      finalY = Math.max(10, finalY);

      setTooltipPos({
        x: finalX,
        y: finalY,
      });
    }
  };

  const exportMapAsPNG = () => {
    const svgElement = mapContainerRef.current?.querySelector("svg");
    if (!svgElement) return;

    try {
      // 1. Compile the lists of provinces under each category dynamically
      const redProvinces = [];
      const orangeProvinces = [];
      const yellowProvinces = [];
      const lightBlueProvinces = [];

      Object.entries(currentDayData.provinces).forEach(([name, p]) => {
        const mm = Math.round(p.rainfall !== undefined ? p.rainfall : (p.rainfall_mm || 0));
        if (mm >= 200) redProvinces.push(name);
        else if (mm >= 100) orangeProvinces.push(name);
        else if (mm >= 50) yellowProvinces.push(name);
        else if (mm >= 25) lightBlueProvinces.push(name);
      });

      redProvinces.sort();
      orangeProvinces.sort();
      yellowProvinces.sort();
      lightBlueProvinces.sort();

      // Helper function to render a clean vertical list of province names
      const renderProvinceList = (provinces, xPos, startY, color) => {
        if (provinces.length === 0) {
          return `<text x="${xPos}" y="${startY}" fill="#475569" font-size="9.5" text-anchor="middle" font-style="italic">None</text>`;
        }

        let markup = "";
        const maxLines = 10; // Allow up to 10 provinces listed in the expanded card space
        for (let i = 0; i < provinces.length; i++) {
          if (i >= maxLines) {
            markup += `<text x="${xPos}" y="${startY + i * 11.5}" fill="${color}" font-size="8.5" font-weight="bold" text-anchor="middle">+ ${provinces.length - maxLines} more</text>`;
            break;
          }
          markup += `<text x="${xPos}" y="${startY + i * 11.5}" fill="#e2e8f0" font-size="9" text-anchor="middle">${provinces[i]}</text>`;
        }
        return markup;
      };

      // Clone the SVG so we can force a full 1400x1400 canvas without affecting on-screen zoom state
      const clonedSvg = svgElement.cloneNode(true);
      clonedSvg.setAttribute("viewBox", "0 0 1400 1400");
      clonedSvg.setAttribute("width", "1400");
      clonedSvg.setAttribute("height", "1400");
      clonedSvg.removeAttribute("style");

      // Dynamic Title, Legend, and Metrics injection programmatically (so they only appear on the saved image)
      const svgNS = "http://www.w3.org/2000/svg";

      // 1. Dynamic Map Title Block (Scaled Up for High Readability)
      const titleGroup = document.createElementNS(svgNS, "g");
      titleGroup.setAttribute("transform", "translate(1010, 60)");
      titleGroup.setAttribute("font-family", "monospace");
      titleGroup.innerHTML = selectedMode === "realtime" ? `
        <rect x="0" y="0" width="370" height="240" rx="14" fill="rgba(9, 13, 22, 0.9)" stroke="rgba(255, 255, 255, 0.15)" stroke-width="1.2" />
        <text x="25" y="40" fill="#34d399" font-size="15" font-weight="bold" letter-spacing="1.5">REALTIME SATELLITE RAIN</text>
        <text x="25" y="65" fill="#f1f5f9" font-size="13" font-weight="bold" font-family="sans-serif">JAXA GSMaP / NASA GPM</text>
        <line x1="25" y1="80" x2="345" y2="80" stroke="rgba(255, 255, 255, 0.12)" stroke-width="1" />
        <text x="25" y="108" fill="#e2e8f0" font-size="11" font-weight="bold" font-family="sans-serif">OBSERVATION TIMEFRAME:</text>
        <text x="25" y="132" fill="#34d399" font-size="11.5" font-weight="bold">${realtimeData?.frames?.[selectedRealtimeFrameIdx]?.formattedTime || "Live Satellite"}</text>
        <line x1="25" y1="192" x2="345" y2="192" stroke="rgba(255, 255, 255, 0.08)" stroke-width="1" />
        <text x="25" y="215" fill="#64748b" font-size="10.5">Source: Global Rainfall Watch</text>
      ` : `
        <rect x="0" y="0" width="370" height="240" rx="14" fill="rgba(9, 13, 22, 0.9)" stroke="rgba(255, 255, 255, 0.15)" stroke-width="1.2" />
        <text x="25" y="40" fill="#38bdf8" font-size="15" font-weight="bold" letter-spacing="1.5">24-HOUR RAINFALL (DAY ${selectedDay})</text>
        <text x="25" y="65" fill="#f1f5f9" font-size="13" font-weight="bold" font-family="sans-serif">${advisoryData?.system}</text>
        <line x1="25" y1="80" x2="345" y2="80" stroke="rgba(255, 255, 255, 0.12)" stroke-width="1" />
        <text x="25" y="108" fill="#e2e8f0" font-size="11" font-weight="bold" font-family="sans-serif">FORECAST VALIDITY WINDOW:</text>
        <text x="25" y="132" fill="#38bdf8" font-size="11.5" font-weight="bold">${currentDayData?.validity?.split(" to ")?.[0] || ""}</text>
        <text x="25" y="152" fill="#64748b" font-size="10.5" font-weight="bold">to</text>
        <text x="25" y="172" fill="#38bdf8" font-size="11.5" font-weight="bold">${currentDayData?.validity?.split(" to ")?.[1] || ""}</text>
        <line x1="25" y1="192" x2="345" y2="192" stroke="rgba(255, 255, 255, 0.08)" stroke-width="1" />
        <text x="25" y="215" fill="#64748b" font-size="10.5">Model Run: ${advisoryData?.init_time}</text>
      `;
      clonedSvg.appendChild(titleGroup);

      // 2. Warning Level Legend Box (Scaled Up for High Readability)
      const legendGroup = document.createElementNS(svgNS, "g");
      legendGroup.setAttribute("transform", "translate(1010, 320)");
      legendGroup.setAttribute("font-family", "sans-serif");
      legendGroup.innerHTML = `
        <rect x="0" y="0" width="370" height="370" rx="14" fill="rgba(9, 13, 22, 0.9)" stroke="rgba(255, 255, 255, 0.15)" stroke-width="1.2" />
        <text x="25" y="38" fill="#38bdf8" font-size="13" font-weight="bold" letter-spacing="1.5" font-family="monospace">WARNING LEVEL LEGEND</text>
        <line x1="25" y1="50" x2="345" y2="50" stroke="rgba(255, 255, 255, 0.12)" stroke-width="1" />
        <rect x="25" y="68" width="24" height="24" rx="6" fill="#DC2626" stroke="rgba(255, 255, 255, 0.2)" stroke-width="0.5" />
        <text x="62" y="85" fill="#f1f5f9" font-size="13" font-weight="bold">${selectedMode === 'realtime' ? 'Torrential Rain (>30 mm/hr)' : 'Red Warning (200+ mm)'}</text>
        <text x="62" y="102" fill="#94a3b8" font-size="10.5">${selectedMode === 'realtime' ? 'Dangerous torrential downpour' : 'Severe widespread flooding & landslides'}</text>
        <rect x="25" y="124" width="24" height="24" rx="6" fill="#F97316" stroke="rgba(255, 255, 255, 0.2)" stroke-width="0.5" />
        <text x="62" y="141" fill="#f1f5f9" font-size="13" font-weight="bold">${selectedMode === 'realtime' ? 'Heavy Rain (15-30 mm/hr)' : 'Orange Alert (100 - 200 mm)'}</text>
        <text x="62" y="158" fill="#94a3b8" font-size="10.5">${selectedMode === 'realtime' ? 'High intensity rain' : 'High risk of flooding & soil slides'}</text>
        <rect x="25" y="180" width="24" height="24" rx="6" fill="#EAB308" stroke="rgba(255, 255, 255, 0.2)" stroke-width="0.5" />
        <text x="62" y="197" fill="#f1f5f9" font-size="13" font-weight="bold">${selectedMode === 'realtime' ? 'Moderate Rain (7.5-15 mm/hr)' : 'Yellow Advisory (50 - 100 mm)'}</text>
        <text x="62" y="214" fill="#94a3b8" font-size="10.5">${selectedMode === 'realtime' ? 'Moderate steady rain' : 'Localized pooling & minor flooding'}</text>
        <rect x="25" y="236" width="24" height="24" rx="6" fill="#38BDF8" stroke="rgba(255, 255, 255, 0.2)" stroke-width="0.5" />
        <text x="62" y="253" fill="#f1f5f9" font-size="13" font-weight="bold">${selectedMode === 'realtime' ? 'Light Rain (2.5-7.5 mm/hr)' : 'Light Blue Alert (25 - 50 mm)'}</text>
        <text x="62" y="270" fill="#94a3b8" font-size="10.5">${selectedMode === 'realtime' ? 'Light steady rain' : 'Localized minor ponding & wet roads'}</text>
        <rect x="25" y="292" width="24" height="24" rx="6" fill="#334155" stroke="rgba(255, 255, 255, 0.2)" stroke-width="0.5" />
        <text x="62" y="309" fill="#cbd5e1" font-size="13" font-weight="bold">${selectedMode === 'realtime' ? 'Clear / Trace (< 2.5 mm/hr)' : 'Light / No Warning (< 25 mm)'}</text>
        <text x="62" y="326" fill="#64748b" font-size="10.5">${selectedMode === 'realtime' ? 'No significant rain' : 'Isolated light rains or clear skies'}</text>
      `;
      clonedSvg.appendChild(legendGroup);

      // 3. Warning Metrics Summary Box (Scaled Up and Expanded to List Province Names)
      const metricsGroup = document.createElementNS(svgNS, "g");
      metricsGroup.setAttribute("transform", "translate(1010, 710)");
      metricsGroup.setAttribute("font-family", "sans-serif");

      const redListMarkup = renderProvinceList(redProvinces, 38, 92, "#ef4444");
      const orangeListMarkup = renderProvinceList(orangeProvinces, 38, 92, "#fb923c");
      const yellowListMarkup = renderProvinceList(yellowProvinces, 38, 92, "#facc15");
      const lightBlueListMarkup = renderProvinceList(lightBlueProvinces, 38, 92, "#38bdf8");

      metricsGroup.innerHTML = `
        <rect x="0" y="0" width="370" height="290" rx="14" fill="rgba(9, 13, 22, 0.9)" stroke="rgba(255, 255, 255, 0.15)" stroke-width="1.2" />
        <text x="25" y="38" fill="#38bdf8" font-size="13" font-weight="bold" letter-spacing="1.5" font-family="monospace">PROVINCIAL WARNING METRICS</text>
        <line x1="25" y1="50" x2="345" y2="50" stroke="rgba(255, 255, 255, 0.12)" stroke-width="1" />
        
        <g transform="translate(25, 70)">
          <!-- Red Column -->
          <g>
            <rect x="0" y="0" width="76" height="65" rx="10" fill="rgba(220, 38, 38, 0.12)" stroke="rgba(220, 38, 38, 0.25)" stroke-width="1" />
            <text x="38" y="35" fill="#DC2626" font-size="24" font-weight="bold" text-anchor="middle">${warningMetrics.red}</text>
            <text x="38" y="52" fill="#ef4444" font-size="9" font-weight="bold" text-anchor="middle" letter-spacing="0.5">RED</text>
            <line x1="8" y1="78" x2="68" y2="78" stroke="rgba(255, 255, 255, 0.08)" stroke-width="0.8" />
            ${redListMarkup}
          </g>

          <!-- Orange Column -->
          <g transform="translate(81, 0)">
            <rect x="0" y="0" width="76" height="65" rx="10" fill="rgba(249, 115, 22, 0.12)" stroke="rgba(249, 115, 22, 0.25)" stroke-width="1" />
            <text x="38" y="35" fill="#F97316" font-size="24" font-weight="bold" text-anchor="middle">${warningMetrics.orange}</text>
            <text x="38" y="52" fill="#fb923c" font-size="9" font-weight="bold" text-anchor="middle" letter-spacing="0.5">ORANGE</text>
            <line x1="8" y1="78" x2="68" y2="78" stroke="rgba(255, 255, 255, 0.08)" stroke-width="0.8" />
            ${orangeListMarkup}
          </g>

          <!-- Yellow Column -->
          <g transform="translate(162, 0)">
            <rect x="0" y="0" width="76" height="65" rx="10" fill="rgba(234, 179, 8, 0.12)" stroke="rgba(234, 179, 8, 0.25)" stroke-width="1" />
            <text x="38" y="35" fill="#EAB308" font-size="24" font-weight="bold" text-anchor="middle">${warningMetrics.yellow}</text>
            <text x="38" y="52" fill="#facc15" font-size="9" font-weight="bold" text-anchor="middle" letter-spacing="0.5">YELLOW</text>
            <line x1="8" y1="78" x2="68" y2="78" stroke="rgba(255, 255, 255, 0.08)" stroke-width="0.8" />
            ${yellowListMarkup}
          </g>

          <!-- Light Blue Column -->
          <g transform="translate(243, 0)">
            <rect x="0" y="0" width="76" height="65" rx="10" fill="rgba(56, 189, 248, 0.12)" stroke="rgba(56, 189, 248, 0.25)" stroke-width="1" />
            <text x="38" y="35" fill="#38BDF8" font-size="24" font-weight="bold" text-anchor="middle">${warningMetrics.lightBlue}</text>
            <text x="38" y="52" fill="#38bdf8" font-size="9" font-weight="bold" text-anchor="middle" letter-spacing="0.5">LT BLUE</text>
            <line x1="8" y1="78" x2="68" y2="78" stroke="rgba(255, 255, 255, 0.08)" stroke-width="0.8" />
            ${lightBlueListMarkup}
          </g>
        </g>
      `;
      clonedSvg.appendChild(metricsGroup);

      const serializer = new XMLSerializer();
      let svgString = serializer.serializeToString(clonedSvg);

      const svgBlob = new Blob([svgString], { type: "image/svg+xml;charset=utf-8" });
      const URL = window.URL || window.webkitURL || window;
      const blobURL = URL.createObjectURL(svgBlob);

      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement("canvas");
        canvas.width = 1400;
        canvas.height = 1400;
        const ctx = canvas.getContext("2d");

        // Premium deep dark slate canvas background
        ctx.fillStyle = "#020617";
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

        const pngURL = canvas.toDataURL("image/png");
        const downloadLink = document.createElement("a");
        downloadLink.href = pngURL;
        downloadLink.download = `PH_Weather_Advisory_${new Date().toISOString().split('T')[0]}.png`;
        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);

        URL.revokeObjectURL(blobURL);
      };

      img.src = blobURL;
    } catch (err) {
      console.error("Failed to export SVG map as PNG:", err);
    }
  };

  // Weather radar/met loading screen
  if (!geoData || !advisoryData) {
    return (
      <div className="flex flex-col items-center justify-center h-[calc(100vh-64px)] w-full bg-slate-950 text-slate-300">
        <div className="relative flex items-center justify-center">
          <div className="absolute w-24 h-24 rounded-full border-2 border-sky-500/25 animate-ping" />
          <div className="absolute w-16 h-16 rounded-full border-2 border-sky-400/40 animate-pulse" />
          <Compass className="w-14 h-14 text-sky-400 animate-spin" style={{ animationDuration: '3s' }} />
        </div>
        <h2 className="mt-8 text-xl font-bold tracking-widest uppercase text-sky-400">Loading Weather Advisories</h2>
        <p className="mt-2 text-xs text-slate-500 font-mono">Loading dynamic province map overlays & ECMWF forecasts...</p>
      </div>
    );
  }

  const activeDisplayProvince = hoveredProvince || selectedProvince;

  return (
    <div className="relative h-[calc(100vh-64px)] w-full bg-slate-950 font-sans overflow-hidden flex flex-col md:flex-row">
      
      {/* ── MOBILE TAB SWITCHER (Only shown on <768px screens) ── */}
      <div className="flex md:hidden bg-slate-900 border-b border-slate-800/80 text-xs font-bold text-slate-400 z-30 shrink-0">
        <button
          onClick={() => setActiveTab("map")}
          className={`flex-1 py-3.5 flex items-center justify-center gap-2 border-b-2 transition-all ${
            activeTab === "map"
              ? "border-sky-500 text-white bg-slate-950/45"
              : "border-transparent hover:text-slate-200"
          }`}
        >
          <MapIcon className="w-4 h-4" />
          Interactive Map
        </button>
        <button
          onClick={() => setActiveTab("bulletin")}
          className={`flex-1 py-3.5 flex items-center justify-center gap-2 border-b-2 transition-all ${
            activeTab === "bulletin"
              ? "border-sky-500 text-white bg-slate-950/45"
              : "border-transparent hover:text-slate-200"
          }`}
        >
          <FileText className="w-4 h-4" />
          Bulletin Desk
        </button>
      </div>

      {/* ── INTERACTIVE DYNAMIC MAP CONTAINER ── */}
      <div
        ref={mapContainerRef}
        onMouseMove={handleMouseMove}
        className={`relative w-full bg-[#020617] overflow-hidden flex items-center justify-center transition-all duration-300 ${
          activeTab === "map" ? "flex flex-1 h-[calc(100vh-112px)]" : "hidden"
        } md:flex md:flex-1 md:h-full`}
      >
        {/* Radar-like background grid lines */}
        <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(ellipse_at_center,rgba(15,23,42,0.6)_0%,rgba(2,6,23,1)_95%)]" />

        {/* Dynamic Zooming SVG Map Canvas */}
        {mapData && (
          <svg
            className="w-auto h-full max-h-full max-w-full aspect-[1000/1400] relative z-10 select-none cursor-crosshair transition-all duration-[1200ms] ease-[cubic-bezier(0.2,0.8,0.2,1)]"
            viewBox={activeViewBox}
            style={{
              filter: "drop-shadow(0 25px 50px rgba(0, 0, 0, 0.4))",
            }}
            onClick={() => {
              setHoveredProvince(null);
              setSelectedProvince(null);
              setIsTooltipVisible(false);
            }}
          >
            {/* Fine Technical Grid Lines */}
            <defs>
              <pattern id="grid" width="100" height="100" patternUnits="userSpaceOnUse">
                <path d="M 100 0 L 0 0 0 100" fill="none" stroke="rgba(51, 65, 85, 0.15)" strokeWidth="0.8" />
              </pattern>
            </defs>
            <rect width={mapData.canvasWidth} height={mapData.canvasHeight} fill="url(#grid)" />

            {/* Latitude/Longitude tick labels */}
            <g opacity="0.15" className="text-[11px] font-mono fill-slate-500">
              <text x="10" y="20">18.5°N</text>
              <text x="10" y="470">15.0°N</text>
              <text x="10" y="930">10.0°N</text>
              <text x="10" y="1380">5.5°N</text>
              <text x="920" y="1390" textAnchor="end">126.5°E</text>
              <text x="470" y="1390" textAnchor="end">121.5°E</text>
              <text x="50" y="1390" textAnchor="end">117.0°E</text>
            </g>

            {/* Vintage meteorological compass rose */}
            <g transform="translate(90, 135)" className="opacity-[0.25] pointer-events-none font-mono">
              <circle r="48" fill="none" stroke="rgba(255,255,255,0.2)" strokeWidth="1" />
              <circle r="40" fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="0.8" strokeDasharray="2 3" />
              <line x1="0" y1="-55" x2="0" y2="55" stroke="rgba(255,255,255,0.25)" strokeWidth="0.8" />
              <line x1="-55" y1="0" x2="55" y2="0" stroke="rgba(255,255,255,0.25)" strokeWidth="0.8" />

              {/* North Arrow Pointer */}
              <polygon points="0,-52 4,-12 0,0 -4,-12" fill="rgba(255,255,255,0.4)" />
              <polygon points="0,52 3,12 0,0 -3,12" fill="rgba(255,255,255,0.15)" />
              <polygon points="52,0 12,3 0,0 12,-3" fill="rgba(255,255,255,0.15)" />
              <polygon points="-52,0 -12,3 0,0 -12,-3" fill="rgba(255,255,255,0.15)" />

              <text x="0" y="-60" textAnchor="middle" fill="rgba(255,255,255,0.6)" fontSize="10" fontWeight="bold">N</text>
              <text x="64" y="3" textAnchor="middle" fill="rgba(255,255,255,0.4)" fontSize="8">E</text>
              <text x="0" y="69" textAnchor="middle" fill="rgba(255,255,255,0.4)" fontSize="8">S</text>
              <text x="-64" y="3" textAnchor="middle" fill="rgba(255,255,255,0.4)" fontSize="8">W</text>
            </g>

            {/* Render all Province Paths dynamically */}
            <g>
              {mapData.features.map((feature) => {
                const provData = currentDayData.provinces[feature.name] || {};
                const rainfall = provData.rainfall !== undefined ? provData.rainfall : (provData.rainfall_mm || 0);
                const isHovered = hoveredProvince?.id === feature.id;
                const isSelected = selectedProvince?.id === feature.id;
                const isActive = isHovered || isSelected;
                const hazardVal = activeHazard === "Wind" ? (provData.wind_kph || 0) : rainfall;
                const fill = getHazardColor(hazardVal);

                return (
                  <path
                    key={feature.id}
                    d={feature.d}
                    fill={fill}
                    stroke={isActive ? "#ffffff" : "rgba(15, 23, 42, 0.4)"}
                    strokeWidth={isActive ? 2.5 : 0.8}
                    strokeLinejoin="round"
                    className="transition-all duration-300 cursor-pointer"
                    style={{
                      opacity: hoveredProvince
                        ? (isHovered ? 1 : 0.35)
                        : (selectedProvince ? (isSelected ? 1 : 0.45) : 1),
                      filter: isActive ? "drop-shadow(0 0 8px rgba(255,255,255,0.4)) brightness(1.15)" : "none"
                    }}
                    onMouseEnter={() => {
                      setHoveredProvince({
                        ...feature,
                        ...provData,
                        rainfall,
                        alert: getAlertLevel(rainfall)
                      });
                      setIsTooltipVisible(true);
                    }}
                    onMouseLeave={() => {
                      setHoveredProvince(null);
                      setIsTooltipVisible(false);
                    }}
                    onClick={(e) => {
                      e.stopPropagation();
                      const currentProv = {
                        ...feature,
                        ...provData,
                        rainfall,
                        alert: getAlertLevel(rainfall)
                      };
                      if (selectedProvince?.id === feature.id) {
                        setSelectedProvince(null);
                      } else {
                        setSelectedProvince(currentProv);
                      }
                    }}
                  />
                );
              })}
            </g>

            {/* Uncolored Overlays to cover warning colors in Laguna de Bay and Taal Volcano */}
            <g pointerEvents="none">
              {mapData.lagunaDeBayPath && (
                <path d={mapData.lagunaDeBayPath} fill="#020617" stroke="rgba(15, 23, 42, 0.4)" strokeWidth={0.8} />
              )}
              {mapData.taalLakePath && (
                <path d={mapData.taalLakePath} fill="#020617" stroke="rgba(15, 23, 42, 0.4)" strokeWidth={0.8} />
              )}
              {mapData.taalVolcanoPath && (
                <path d={mapData.taalVolcanoPath} fill="#020617" stroke="rgba(15, 23, 42, 0.4)" strokeWidth={0.8} />
              )}
            </g>

            {/* Interactive Province Labels */}
            <g className="pointer-events-none select-none font-mono">
              {mapData.features.map((feature) => {
                const rainfall = currentDayData.provinces[feature.name]?.rainfall !== undefined
                  ? currentDayData.provinces[feature.name].rainfall
                  : (currentDayData.provinces[feature.name]?.rainfall_mm || 0);
                const isHovered = hoveredProvince?.id === feature.id;
                const isSelected = selectedProvince?.id === feature.id;
                const isActive = isHovered || isSelected;

                if (showLabels && feature.centroid && (rainfall >= 50 || isActive)) {
                  return (
                    <g key={`lbl-${feature.id}`} transform={`translate(${feature.centroid[0]}, ${feature.centroid[1]})`}>
                      <rect
                        x={-(feature.name.length * 3.2 + 6)}
                        y="-15"
                        width={feature.name.length * 6.4 + 12}
                        height="18"
                        rx="4"
                        fill="rgba(15, 23, 42, 0.85)"
                        stroke="rgba(255,255,255,0.15)"
                        strokeWidth="0.5"
                      />
                      <text
                        y="-3"
                        textAnchor="middle"
                        fill={isActive ? "#ffffff" : "#cbd5e1"}
                        fontSize="8.5"
                        fontWeight={rainfall >= 100 ? "bold" : "normal"}
                      >
                        {feature.name}
                      </text>
                    </g>
                  );
                }
                return null;
              })}
            </g>
          </svg>
        )}

        {/* Floating Controller overlay */}
        <div className="absolute top-4 left-4 right-4 z-20 flex flex-row md:flex-col items-center md:items-start gap-2 flex-wrap pointer-events-none">
          {/* Island Group Selector */}
          <div className="bg-slate-950/80 backdrop-blur-md p-1 rounded-lg border border-slate-800/80 shadow-xl flex gap-1 pointer-events-auto">
            {["All", "Luzon", "Visayas", "Mindanao"].map((region) => (
              <button
                key={region}
                onClick={() => setActiveRegion(region)}
                className={`px-2 py-1 rounded text-[9px] sm:text-xs font-bold tracking-wide uppercase cursor-pointer transition-all duration-300 ${
                  activeRegion === region
                    ? "bg-sky-500 text-white shadow-md shadow-sky-500/10 scale-105"
                    : "text-slate-400 hover:text-slate-200 hover:bg-slate-900/50"
                }`}
              >
                {region}
              </button>
            ))}
          </div>

          <div className="flex gap-2 pointer-events-auto">
            {/* Toggle Map Labels */}
            <button
              onClick={() => setShowLabels(!showLabels)}
              className={`px-2 py-1.5 rounded-lg text-[9px] sm:text-xs font-semibold backdrop-blur-md border shadow-lg flex items-center justify-center gap-1 cursor-pointer transition-all duration-300 ${
                showLabels
                  ? "bg-emerald-600/80 text-white border-emerald-500"
                  : "bg-slate-950/80 text-slate-400 border-slate-800 hover:bg-slate-900/80"
              }`}
            >
              <Layers className="w-3.5 h-3.5" />
              <span>{showLabels ? "Hide Names" : "Names"}</span>
            </button>

            {/* Export PNG Button */}
            <button
              onClick={exportMapAsPNG}
              className="px-2 py-1.5 rounded-lg text-[9px] sm:text-xs font-semibold backdrop-blur-md border shadow-lg flex items-center justify-center gap-1 cursor-pointer bg-slate-950/80 text-slate-400 border-slate-800 hover:bg-slate-900/80 hover:text-sky-400 transition-all duration-300"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export</span>
            </button>
          </div>
        </div>

        {/* Realtime JAXA GSMaP Observation Map Badge */}
        {selectedMode === "realtime" && (
          <div className="hidden md:flex absolute top-4 right-4 z-20 pointer-events-none bg-slate-950/90 border border-emerald-500/40 text-emerald-300 backdrop-blur-md px-3.5 py-2 rounded-xl shadow-2xl items-center gap-2.5 font-mono text-[10px] font-bold">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-ping inline-block" />
            <div className="flex flex-col">
              <span className="text-[9px] text-emerald-400 uppercase tracking-widest font-black">JAXA GSMaP Realtime</span>
              <span className="text-white font-bold">{realtimeData?.frames?.[selectedRealtimeFrameIdx]?.formattedTime || "Live Satellite Data"}</span>
            </div>
          </div>
        )}

        {/* ── DYNAMIC CURSOR FLOATING GLASS TOOLTIP (DESKTOP ONLY) ── */}
        {isTooltipVisible && hoveredProvince && (
          <div
            className="hidden md:flex absolute z-50 pointer-events-none w-72 rounded-xl border border-slate-700/60 bg-slate-950/90 p-4 text-slate-200 shadow-2xl backdrop-blur-lg transition-opacity duration-200 flex flex-col gap-2.5"
            style={{
              left: tooltipPos.x,
              top: tooltipPos.y,
              transform: "translate3d(0, 0, 0)"
            }}
          >
            {/* Tooltip Header */}
            <div className="flex justify-between items-start border-b border-slate-800 pb-2">
              <div>
                <h3 className="font-bold text-slate-100 text-sm tracking-wide">{hoveredProvince.name}</h3>
                <p className="text-[10px] font-semibold text-sky-400 uppercase tracking-wider mt-0.5">
                  {hoveredProvince.group} • {hoveredProvince.region.split("(")[0].trim()}
                </p>
              </div>
              <MapPin className="w-4 h-4 text-sky-400 opacity-80" />
            </div>

            {/* Precipitation reading metrics */}
            <div className="flex items-center gap-4 bg-slate-900/60 px-3 py-2 rounded-lg border border-slate-800">
              <div className="flex items-center justify-center w-8 h-8 rounded-full bg-sky-500/10 text-sky-400">
                <CloudRain className="w-4 h-4 animate-pulse" />
              </div>
                            <div>
                <p className="text-[10px] text-slate-500 font-mono uppercase tracking-wider">
                  {selectedMode === "realtime" ? "Observed Rain" : (activeHazard === "Wind" ? "Max Wind Gust" : "Forecast Rainfall")}
                </p>
                {activeHazard === "Wind" ? (
                  <p className="text-base font-bold text-white tracking-wide mt-1">
                    {Math.round(hoveredProvince.wind_kph || 0)} <span className="text-xs font-normal text-slate-400">kph</span>
                  </p>
                ) : (
                  selectedMode === "forecast" && hoveredProvince.min_rainfall !== undefined && hoveredProvince.max_rainfall !== undefined ? (
                    <p className="text-base font-bold text-white tracking-wide leading-tight mt-1">
                      {Math.round(hoveredProvince.min_rainfall)} - {Math.round(hoveredProvince.max_rainfall)} <span className="text-[10px] font-medium text-slate-400 font-sans">mm/24h</span>
                      <br /><span className="text-[9px] font-normal text-slate-400 block mt-0.5">Peak Consensus: {Math.round(hoveredProvince.rainfall)} mm</span>
                    </p>
                  ) : (
                    <p className="text-base font-bold text-white tracking-wide mt-1">
                      {Math.round(hoveredProvince.rainfall)} <span className="text-xs font-normal text-slate-400">mm / 24h</span>
                    </p>
                  )
                )}
              </div>
            </div>

            {/* Confidence & Agreement */}
            {hoveredProvince.confidence && (
              <div className="bg-slate-900/40 px-3 py-2 rounded-lg border border-slate-800/80 text-[10px] font-mono flex flex-col gap-1">
                <div className="flex justify-between items-center text-slate-400">
                  <span>Confidence:</span>
                  <span className={`font-bold ${
                    hoveredProvince.confidence.includes('High') ? 'text-emerald-400' :
                    hoveredProvince.confidence.includes('Medium') ? 'text-yellow-400' : 'text-red-400'
                  }`}>{hoveredProvince.confidence} ({hoveredProvince.agreement}% agreement)</span>
                </div>
                {hoveredProvince.models && (
                  <div className="flex justify-between items-center text-slate-500 text-[9px] border-t border-slate-900 pt-1.5 mt-0.5">
                    {hoveredProvince.models.GSMaP !== undefined ? (
                      <>
                        <span>JAXA GSMaP: {Math.round(hoveredProvince.models.GSMaP)} {activeHazard === "Wind" ? "kph" : "mm"}</span>
                        <span>GPM Satellite: {Math.round(hoveredProvince.models.GPM)} {activeHazard === "Wind" ? "kph" : "mm"}</span>
                      </>
                    ) : (
                      <>
                        <span>IFS: {Math.round(activeHazard === "Wind" && hoveredProvince.wind_models ? hoveredProvince.wind_models.IFS : hoveredProvince.models.IFS)} {activeHazard === "Wind" ? "kph" : "mm"}</span>
                        <span>AIFS: {Math.round(activeHazard === "Wind" && hoveredProvince.wind_models ? hoveredProvince.wind_models.AIFS : hoveredProvince.models.AIFS)} {activeHazard === "Wind" ? "kph" : "mm"}</span>
                      </>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* Custom localized advisory actions */}
            <div className={`p-2.5 rounded-lg border text-xs leading-relaxed flex flex-col gap-1 ${hoveredProvince.alert.style}`}>
              <div className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-[10px]">
                <ShieldAlert className="w-3.5 h-3.5" />
                <span>{hoveredProvince.alert.title}</span>
              </div>
              <p className="opacity-90">{hoveredProvince.alert.text}</p>
            </div>
          </div>
        )}

        {/* ── DESKTOP FIXED SELECTED PROVINCE CARD (Only shown on Desktop) ── */}
        {selectedProvince && (
          <div className="hidden md:flex absolute bottom-4 left-4 z-30 w-80 rounded-xl border border-slate-700/60 bg-slate-950/95 p-4 text-slate-200 shadow-2xl backdrop-blur-lg flex flex-col gap-2.5 animate-in fade-in slide-in-from-bottom-5 duration-300">
            <div className="flex justify-between items-start border-b border-slate-800 pb-2">
              <div>
                <h3 className="font-bold text-slate-100 text-sm tracking-wide">{selectedProvince.name}</h3>
                <p className="text-[10px] font-semibold text-sky-400 uppercase tracking-wider mt-0.5">
                  {selectedProvince.group} • {selectedProvince.region.split("(")[0].trim()}
                </p>
              </div>
              <div className="flex items-center gap-1.5">
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setSelectedProvince(null);
                  }}
                  className="p-1 rounded-md hover:bg-slate-900 text-slate-400 hover:text-white transition-colors cursor-pointer border border-transparent hover:border-slate-800"
                  title="Clear Selection"
                >
                  <X className="w-4 h-4" />
                </button>
                <MapPin className="w-4 h-4 text-sky-400 opacity-80" />
              </div>
            </div>

            <div className="flex items-center gap-4 bg-slate-900/60 px-3 py-2 rounded-lg border border-slate-800">
              <div className="flex items-center justify-center w-8 h-8 rounded-full bg-sky-500/10 text-sky-400">
                <CloudRain className="w-4 h-4 animate-pulse" />
              </div>
                            <div>
                <p className="text-[10px] text-slate-500 font-mono uppercase tracking-wider">
                  {selectedMode === "realtime" ? "Observed Rain" : (activeHazard === "Wind" ? "Max Wind Gust" : "Forecast Rainfall")}
                </p>
                {activeHazard === "Wind" ? (
                  <p className="text-base font-bold text-white tracking-wide mt-1">
                    {Math.round(selectedProvince.wind_kph || 0)} <span className="text-xs font-normal text-slate-400 font-sans">kph</span>
                  </p>
                ) : (
                  selectedMode === "forecast" && selectedProvince.min_rainfall !== undefined && selectedProvince.max_rainfall !== undefined ? (
                    <p className="text-base font-bold text-white tracking-wide leading-tight mt-1">
                      {Math.round(selectedProvince.min_rainfall)} - {Math.round(selectedProvince.max_rainfall)} <span className="text-[10px] font-medium text-slate-400 font-sans">mm/24h</span>
                      <br /><span className="text-[9px] font-normal text-slate-400 block mt-0.5">Peak Consensus: {Math.round(selectedProvince.rainfall)} mm</span>
                    </p>
                  ) : (
                    <p className="text-base font-bold text-white tracking-wide mt-1">
                      {Math.round(selectedProvince.rainfall)} <span className="text-xs font-normal text-slate-400 font-sans">mm / 24h</span>
                    </p>
                  )
                )}
              </div>
            </div>

            {selectedProvince.confidence && (
              <div className="bg-slate-900/40 p-2.5 rounded-lg border border-slate-800/80 text-[10px] font-mono flex flex-col gap-1.5">
                <div className="flex justify-between items-center text-slate-400">
                  <span>Confidence:</span>
                  <span className={`font-bold ${
                    selectedProvince.confidence.includes('High') ? 'text-emerald-400' :
                    selectedProvince.confidence.includes('Medium') ? 'text-yellow-400' : 'text-red-400'
                  }`}>{selectedProvince.confidence} ({selectedProvince.agreement}% agreement)</span>
                </div>
                {selectedProvince.models && (
                  <div className="flex justify-between items-center text-slate-500 text-[9px] border-t border-slate-900 pt-1.5 mt-0.5">
                    {selectedProvince.models.GSMaP !== undefined ? (
                      <>
                        <span>JAXA GSMaP: {Math.round(selectedProvince.models.GSMaP)} {activeHazard === "Wind" ? "kph" : "mm"}</span>
                        <span>GPM Satellite: {Math.round(selectedProvince.models.GPM)} {activeHazard === "Wind" ? "kph" : "mm"}</span>
                      </>
                    ) : (
                      <>
                        <span>IFS: {Math.round(activeHazard === "Wind" && selectedProvince.wind_models ? selectedProvince.wind_models.IFS : selectedProvince.models.IFS)} {activeHazard === "Wind" ? "kph" : "mm"}</span>
                        <span>AIFS: {Math.round(activeHazard === "Wind" && selectedProvince.wind_models ? selectedProvince.wind_models.AIFS : selectedProvince.models.AIFS)} {activeHazard === "Wind" ? "kph" : "mm"}</span>
                      </>
                    )}
                  </div>
                )}
              </div>
            )}

            <div className={`p-2.5 rounded-lg border text-xs leading-relaxed flex flex-col gap-1 ${selectedProvince.alert.style}`}>
              <div className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-[10px]">
                <ShieldAlert className="w-3.5 h-3.5" />
                <span>{selectedProvince.alert.title}</span>
              </div>
              <p className="opacity-90">{selectedProvince.alert.text}</p>
            </div>
          </div>
        )}
      </div>

      {/* ── SIDEBAR PANEL (PAGASA WEATHER ALERT DESK STYLE) ── */}
      <div
        className={`w-full md:w-80 lg:w-96 bg-[#050811]/90 backdrop-blur-xl border-t md:border-t-0 md:border-l border-slate-800/80 flex flex-col z-20 overflow-hidden shadow-[-15px_0_35px_rgba(0,0,0,0.6)] ${
          activeTab === "bulletin" ? "flex flex-1 h-[calc(100vh-112px)]" : "hidden"
        } md:flex md:h-full md:flex-none`}
      >
        {/* PAGASA Style Header */}
        <div className="bg-gradient-to-r from-sky-950/80 to-blue-950/80 border-b border-sky-800/40 text-center relative overflow-hidden flex-shrink-0 p-5">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(14,165,233,0.1)_0%,transparent_70%)] pointer-events-none" />
          <h1 className="text-lg font-black tracking-widest text-white uppercase flex items-center justify-center gap-2 relative">
            <ShieldAlert className="w-5 h-5 text-sky-400 animate-pulse" />
            <span>{selectedMode === "realtime" ? "JAXA Realtime Rain" : "Rainfall Forecast"}</span>
          </h1>
          <p className="text-xs font-semibold text-sky-300 uppercase tracking-widest mt-1">
            {selectedMode === "realtime" ? "Satellite Precipitation (GSMaP)" : "24-Hour Advisory Bulletin"}
          </p>
          {selectedMode === "forecast" && currentDayData && (
            <div className="mt-3 flex flex-col gap-1.5 items-center">
              <span className="text-[10px] text-slate-300 font-mono bg-slate-950/70 py-1 px-3 rounded-full border border-slate-800/60 w-fit text-center">
                {currentDayData.validity}
              </span>
              <span className="text-[9px] text-slate-400 font-mono uppercase tracking-wider">
                Model Run: {advisoryData.init_time}
              </span>
            </div>
          )}
          {selectedMode === "realtime" && realtimeData && (
            <div className="mt-3 flex flex-col gap-1.5 items-center">
              <span className="text-[10px] text-emerald-400 font-mono bg-slate-950/80 py-1 px-3 rounded-full border border-emerald-500/40 w-fit text-center font-bold">
                Observed: {realtimeData.frames?.[selectedRealtimeFrameIdx]?.formattedTime || "Live"}
              </span>
              <span className="text-[9px] text-slate-400 font-mono uppercase tracking-wider">
                Source: {realtimeData.provider?.replace(" (hokusai.eorc.jaxa.jp)", "") || "JAXA GSMaP / GPM"}
              </span>
            </div>
          )}
        </div>

        {/* Mode Selector Tabs (Realtime vs Forecast) */}
        <div className="px-4 pt-3 pb-2 bg-slate-950/80 border-b border-slate-900 flex flex-col gap-2 flex-shrink-0">
          <div className="grid grid-cols-2 gap-1 p-0.5 rounded-lg bg-slate-900/80 border border-slate-800/80">
            <button
              onClick={() => setSelectedMode("realtime")}
              className={`py-1.5 px-2 rounded-md text-[10px] font-bold tracking-wide uppercase transition-all flex items-center justify-center gap-1.5 cursor-pointer ${
                selectedMode === "realtime"
                  ? "bg-emerald-600 text-white shadow-md shadow-emerald-600/20"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              <CloudRain className="w-3.5 h-3.5" />
              <span>Realtime (GSMaP)</span>
            </button>
            <button
              onClick={() => setSelectedMode("forecast")}
              className={`py-1.5 px-2 rounded-md text-[10px] font-bold tracking-wide uppercase transition-all flex items-center justify-center gap-1.5 cursor-pointer ${
                selectedMode === "forecast"
                  ? "bg-sky-500 text-white shadow-md shadow-sky-500/20"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>5-Day Forecast</span>
            </button>
          </div>
          {selectedMode === "forecast" && (
            <div className="grid grid-cols-2 gap-1 p-0.5 rounded-lg bg-slate-900/80 border border-slate-800/80 mt-1">
              <button
                onClick={() => setActiveHazard("Rainfall")}
                className={`py-1.5 px-2 rounded-md text-[10px] font-bold tracking-wide uppercase transition-all flex items-center justify-center gap-1.5 cursor-pointer ${
                  activeHazard === "Rainfall"
                    ? "bg-sky-500 text-white shadow-md shadow-sky-500/20"
                    : "text-slate-400 hover:text-slate-200"
                }`}
              >
                <CloudRain className="w-3.5 h-3.5" />
                <span>Rainfall</span>
              </button>
              <button
                onClick={() => setActiveHazard("Wind")}
                className={`py-1.5 px-2 rounded-md text-[10px] font-bold tracking-wide uppercase transition-all flex items-center justify-center gap-1.5 cursor-pointer ${
                  activeHazard === "Wind"
                    ? "bg-fuchsia-600 text-white shadow-md shadow-fuchsia-600/20"
                    : "text-slate-400 hover:text-slate-200"
                }`}
              >
                <Compass className="w-3.5 h-3.5" />
                <span>Wind Gusts</span>
              </button>
            </div>
          )}

        </div>

        {/* Timeline Frame Selector (Realtime Mode) OR Day Selector (Forecast Mode) */}
        <div className="px-4 pt-2.5 pb-3 bg-slate-950/50 border-b border-slate-900 flex flex-col gap-2 flex-shrink-0">
          {selectedMode === "realtime" ? (
            <>
              <div className="text-[10px] font-mono text-emerald-400 uppercase tracking-widest text-center flex items-center justify-center gap-1">
                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-ping inline-block" />
                <span>Satellite Observation Timeline:</span>
              </div>
              <div className="grid grid-cols-5 gap-1 p-0.5 rounded-lg bg-slate-900/60 border border-slate-800/60">
                {(realtimeData?.frames || [
                  { label: "Latest", offsetHours: 0 },
                  { label: "1h ago", offsetHours: 1 },
                  { label: "2h ago", offsetHours: 2 },
                  { label: "3h ago", offsetHours: 3 },
                  { label: "6h ago", offsetHours: 6 },
                ]).map((frame, idx) => (
                  <button
                    key={idx}
                    onClick={() => {
                      setSelectedRealtimeFrameIdx(idx);
                      setSelectedProvince(null);
                      setHoveredProvince(null);
                    }}
                    className={`py-1.5 rounded-md text-[9px] font-bold transition-all cursor-pointer ${
                      selectedRealtimeFrameIdx === idx
                        ? "bg-emerald-500 text-slate-950 font-black shadow-md shadow-emerald-500/20 scale-105"
                        : "text-slate-400 hover:text-slate-200"
                    }`}
                  >
                    {frame.label.split(" ")[0]}
                  </button>
                ))}
              </div>
            </>
          ) : (
            <>
              <div className="text-[10px] font-mono text-slate-500 uppercase tracking-widest text-center">Forecast Period:</div>
              <div className="grid grid-cols-5 gap-1 p-0.5 rounded-lg bg-slate-900/60 border border-slate-800/60">
                {[1, 2, 3, 4, 5].map((d) => (
                  <button
                    key={d}
                    onClick={() => {
                      setSelectedDay(d);
                      setSelectedProvince(null);
                      setHoveredProvince(null);
                    }}
                    className={`py-1.5 rounded-md text-[10px] sm:text-xs font-bold transition-all cursor-pointer ${
                      selectedDay === d
                        ? "bg-sky-500 text-white shadow-md shadow-sky-500/10 scale-105"
                        : "text-slate-400 hover:text-slate-200"
                    }`}
                  >
                    Day {d}
                  </button>
                ))}
              </div>
            </>
          )}
        </div>

        {/* Context Card */}
        <div className="p-4 bg-slate-950/30 border-b border-slate-900 flex flex-col gap-3 flex-shrink-0">
          <div>
            <div className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">
              {selectedMode === "realtime" ? "Satellite Provider:" : "Model Forecast:"}
            </div>
            <div className="text-sm font-bold text-sky-400 mt-0.5">
              {selectedMode === "realtime"
                ? (realtimeData?.provider?.replace(" (hokusai.eorc.jaxa.jp)", "") || "JAXA GSMaP / NASA GPM Satellite Network")
                : advisoryData.system}
            </div>
          </div>
        </div>

        {/* ── STATS OVERVIEW DASHBOARD ── */}
        <div className="grid grid-cols-4 gap-2 px-4 py-3 bg-slate-950/60 border-b border-slate-900/60 flex-shrink-0">
          <div className="flex flex-col items-center justify-center p-1.5 rounded-lg bg-red-500/10 border border-red-500/20">
            <span className="text-sm font-mono font-black text-red-500">{warningMetrics.red}</span>
            <span className="text-[8.5px] text-red-400 font-bold uppercase tracking-wider mt-0.5">Red</span>
          </div>
          <div className="flex flex-col items-center justify-center p-1.5 rounded-lg bg-orange-500/10 border border-orange-500/20">
            <span className="text-sm font-mono font-black text-orange-500">{warningMetrics.orange}</span>
            <span className="text-[8.5px] text-orange-400 font-bold uppercase tracking-wider mt-0.5">Orange</span>
          </div>
          <div className="flex flex-col items-center justify-center p-1.5 rounded-lg bg-yellow-500/10 border border-yellow-500/20">
            <span className="text-sm font-mono font-black text-yellow-500">{warningMetrics.yellow}</span>
            <span className="text-[8.5px] text-yellow-400 font-bold uppercase tracking-wider mt-0.5">Yellow</span>
          </div>
          <div className="flex flex-col items-center justify-center p-1.5 rounded-lg bg-sky-500/10 border border-sky-500/20">
            <span className="text-sm font-mono font-black text-sky-500">{warningMetrics.lightBlue}</span>
            <span className="text-[8.5px] text-sky-400 font-bold uppercase tracking-wider mt-0.5">Lt Blue</span>
          </div>
        </div>

        {/* Advisory Action Tables */}
        <div className="p-5 flex-1 overflow-y-auto space-y-5">
          <h2 className="text-slate-400 font-bold uppercase tracking-wider text-[11px] flex items-center gap-1.5 border-b border-slate-800/80 pb-2 mb-4">
            <TrendingUp className="w-3.5 h-3.5 text-sky-400" />
            <span>Threat Warning Categories</span>
          </h2>

          {/* Red Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-red-950 shadow-lg group transition-all duration-300 hover:border-red-900/60">
            <div className="bg-gradient-to-r from-red-700 to-red-600 px-4 py-2 flex justify-between items-center text-white text-xs font-bold tracking-widest uppercase">
              <span>{selectedMode === "realtime" ? "Red Level (>30 mm/hr)" : (activeHazard === "Wind" ? "Typhoon (>118 kph)" : "Red Level (200+ mm)")}</span>
              {warningMetrics.red > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-slate-950 text-[10px] text-red-400 border border-red-500/35 font-bold shadow-md animate-pulse">
                  {warningMetrics.red} Prov
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-red-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">{activeHazard === "Wind" ? "Wind:" : "Flooding:"}</strong> {activeHazard === "Wind" ? "Extreme damage to structures expected." : "Extreme widespread flooding expected."}</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-red-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">{activeHazard === "Wind" ? "Hazards:" : "Landslides:"}</strong> {activeHazard === "Wind" ? "Uprooted trees, power outages." : "Extreme landslides highly likely."}</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-red-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Evacuate immediately.</p>
              </div>

              {/* Affected Provinces Name List */}
              {warningProvinces.red.length > 0 && (
                <div className="pt-3 mt-3 border-t border-slate-900/60">
                  <span className="text-[9.5px] font-bold text-red-400 uppercase tracking-wider block mb-1.5 text-left font-mono">Affected Provinces:</span>
                  <div className="flex flex-wrap gap-1.5 justify-start">
                    {warningProvinces.red.map(p => {
                      const isSelected = selectedProvince?.name === p;
                      const provData = currentDayData.provinces[p] || {};
                      const rainfall = provData.rainfall !== undefined ? provData.rainfall : (provData.rainfall_mm || 0);
                      return (
                        <button
                          key={p}
                          onClick={(e) => {
                            e.stopPropagation();
                            const feature = mapData?.features.find(f => f.name === p) || {};
                            setSelectedProvince({
                              ...feature,
                              name: p,
                              ...provData,
                              rainfall,
                              alert: getAlertLevel(rainfall)
                            });
                            if (window.innerWidth < 768) {
                              setActiveTab("map");
                            }
                          }}
                          className={`px-2 py-0.5 text-[9.5px] font-mono rounded cursor-pointer transition-all duration-200 border ${
                            isSelected
                              ? "bg-red-500 text-white border-red-400 shadow-md shadow-red-500/20 scale-105"
                              : "bg-red-950/40 text-red-300 border-red-900/40 hover:bg-red-900/30 hover:border-red-700"
                          }`}
                        >
                          {p} ({Math.round(activeHazard === "Wind" ? provData.wind_kph : rainfall)}{selectedMode === "realtime" ? "mm/hr" : (activeHazard === "Wind" ? "kph" : "mm")})
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Orange Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-orange-950 shadow-lg group transition-all duration-300 hover:border-orange-900/60">
            <div className="bg-gradient-to-r from-orange-600 to-orange-500 px-4 py-2 flex justify-between items-center text-white text-xs font-bold tracking-widest uppercase">
              <span>{activeHazard === "Wind" ? "Severe TS (89-117 kph)" : "Orange Level (100-200 mm)"}</span>
              {warningMetrics.orange > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-slate-950 text-[10px] text-orange-400 border border-orange-500/35 font-bold shadow-md">
                  {warningMetrics.orange} Prov
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-orange-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Severe lowland flooding likely.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-orange-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Landslides:</strong> Soil saturations high risk.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-orange-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Prepare emergency grab-bags.</p>
              </div>

              {/* Affected Provinces Name List */}
              {warningProvinces.orange.length > 0 && (
                <div className="pt-3 mt-3 border-t border-slate-900/60">
                  <span className="text-[9.5px] font-bold text-orange-400 uppercase tracking-wider block mb-1.5 text-left font-mono">Affected Provinces:</span>
                  <div className="flex flex-wrap gap-1.5 justify-start">
                    {warningProvinces.orange.map(p => {
                      const isSelected = selectedProvince?.name === p;
                      const provData = currentDayData.provinces[p] || {};
                      const rainfall = provData.rainfall !== undefined ? provData.rainfall : (provData.rainfall_mm || 0);
                      return (
                        <button
                          key={p}
                          onClick={(e) => {
                            e.stopPropagation();
                            const feature = mapData?.features.find(f => f.name === p) || {};
                            setSelectedProvince({
                              ...feature,
                              name: p,
                              ...provData,
                              rainfall,
                              alert: getAlertLevel(rainfall)
                            });
                            if (window.innerWidth < 768) {
                              setActiveTab("map");
                            }
                          }}
                          className={`px-2 py-0.5 text-[9.5px] font-mono rounded cursor-pointer transition-all duration-200 border ${
                            isSelected
                              ? "bg-orange-500 text-white border-orange-400 shadow-md shadow-orange-500/20 scale-105"
                              : "bg-orange-950/40 text-orange-300 border-orange-900/40 hover:bg-orange-900/30 hover:border-orange-700"
                          }`}
                        >
                          {p} ({Math.round(activeHazard === "Wind" ? provData.wind_kph : rainfall)}{selectedMode === "realtime" ? "mm/hr" : (activeHazard === "Wind" ? "kph" : "mm")})
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Yellow Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-yellow-950 shadow-lg group transition-all duration-300 hover:border-yellow-900/60">
            <div className="bg-gradient-to-r from-yellow-500 to-yellow-400 px-4 py-2 flex justify-between items-center text-slate-900 text-xs font-extrabold tracking-widest uppercase">
              <span>{activeHazard === "Wind" ? "Tropical Storm (62-88 kph)" : "Yellow Level (50-100 mm)"}</span>
              {warningMetrics.yellow > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-slate-950 text-[10px] text-yellow-400 border border-yellow-500/35 font-bold shadow-md">
                  {warningMetrics.yellow} Prov
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Minor localized pooling possible.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Landslides:</strong> Minor slips cut banks.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Stay tuned to warnings.</p>
              </div>

              {/* Affected Provinces Name List */}
              {warningProvinces.yellow.length > 0 && (
                <div className="pt-3 mt-3 border-t border-slate-900/60">
                  <span className="text-[9.5px] font-bold text-yellow-400 uppercase tracking-wider block mb-1.5 text-left font-mono">Affected Provinces:</span>
                  <div className="flex flex-wrap gap-1.5 justify-start">
                    {warningProvinces.yellow.map(p => {
                      const isSelected = selectedProvince?.name === p;
                      const provData = currentDayData.provinces[p] || {};
                      const rainfall = provData.rainfall !== undefined ? provData.rainfall : (provData.rainfall_mm || 0);
                      return (
                        <button
                          key={p}
                          onClick={(e) => {
                            e.stopPropagation();
                            const feature = mapData?.features.find(f => f.name === p) || {};
                            setSelectedProvince({
                              ...feature,
                              name: p,
                              ...provData,
                              rainfall,
                              alert: getAlertLevel(rainfall)
                            });
                            if (window.innerWidth < 768) {
                              setActiveTab("map");
                            }
                          }}
                          className={`px-2 py-0.5 text-[9.5px] font-mono rounded cursor-pointer transition-all duration-200 border ${
                            isSelected
                              ? "bg-yellow-500 text-slate-950 border-yellow-400 shadow-md shadow-yellow-500/20 scale-105"
                              : "bg-yellow-950/30 text-yellow-300 border-yellow-900/30 hover:bg-yellow-900/20 hover:border-yellow-700"
                          }`}
                        >
                          {p} ({Math.round(activeHazard === "Wind" ? provData.wind_kph : rainfall)}{selectedMode === "realtime" ? "mm/hr" : (activeHazard === "Wind" ? "kph" : "mm")})
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Light Blue Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-sky-950 shadow-lg group transition-all duration-300 hover:border-sky-900/60">
            <div className="bg-gradient-to-r from-sky-600 to-sky-500 px-4 py-2 flex justify-between items-center text-white text-xs font-bold tracking-widest uppercase">
              <span>{activeHazard === "Wind" ? "Depression (39-61 kph)" : "Light Blue Level (25-50 mm)"}</span>
              {warningMetrics.lightBlue > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-slate-950 text-[10px] text-sky-400 border border-sky-500/35 font-bold shadow-md">
                  {warningMetrics.lightBlue} Prov
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-sky-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Low localized ponding on streets.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-sky-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Observe standard road caution.</p>
              </div>

              {/* Affected Provinces Name List */}
              {warningProvinces.lightBlue.length > 0 && (
                <div className="pt-3 mt-3 border-t border-slate-900/60">
                  <span className="text-[9.5px] font-bold text-sky-400 uppercase tracking-wider block mb-1.5 text-left font-mono">Affected Provinces:</span>
                  <div className="flex flex-wrap gap-1.5 justify-start">
                    {warningProvinces.lightBlue.map(p => {
                      const isSelected = selectedProvince?.name === p;
                      const provData = currentDayData.provinces[p] || {};
                      const rainfall = provData.rainfall !== undefined ? provData.rainfall : (provData.rainfall_mm || 0);
                      return (
                        <button
                          key={p}
                          onClick={(e) => {
                            e.stopPropagation();
                            const feature = mapData?.features.find(f => f.name === p) || {};
                            setSelectedProvince({
                              ...feature,
                              name: p,
                              ...provData,
                              rainfall,
                              alert: getAlertLevel(rainfall)
                            });
                            if (window.innerWidth < 768) {
                              setActiveTab("map");
                            }
                          }}
                          className={`px-2 py-0.5 text-[9.5px] font-mono rounded cursor-pointer transition-all duration-200 border ${
                            isSelected
                              ? "bg-sky-500 text-white border-sky-400 shadow-md shadow-sky-500/20 scale-105"
                              : "bg-sky-950/40 text-sky-300 border-sky-900/40 hover:bg-sky-900/30 hover:border-sky-700"
                          }`}
                        >
                          {p} ({Math.round(activeHazard === "Wind" ? provData.wind_kph : rainfall)}{selectedMode === "realtime" ? "mm/hr" : (activeHazard === "Wind" ? "kph" : "mm")})
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Meteorological Footer info */}
        {advisoryData && (
          <div className="bg-slate-950 p-4 border-t border-slate-900 flex flex-col gap-2 relative flex-shrink-0">
            <div className="text-emerald-400 font-bold text-xs text-center tracking-wide uppercase">
              {advisoryData.title}
            </div>
            <div className="flex items-center justify-center gap-3 mt-1 pb-1">
              <img src="/images/logo.png" alt="Logo" className="h-7 w-7 opacity-85 object-contain" />
              <div className="text-[9px] text-slate-500 font-mono leading-tight">
                {advisoryData.system}<br />
                Weather Analysis & Forecasting Desk
              </div>
            </div>
          </div>
        )}
      </div>

      {/* ── MOBILE SLIDE-UP GLASS BOTTOM-SHEET PANEL ── */}
      {activeDisplayProvince && (
        <div className="fixed bottom-0 left-0 right-0 z-50 md:hidden bg-slate-950/98 border-t border-slate-800 rounded-t-2xl pb-8 pt-4 px-5 shadow-[0_-10px_35px_rgba(0,0,0,0.85)] backdrop-blur-xl animate-in slide-in-from-bottom-full duration-300">
          {/* Drawer Grab Indicator */}
          <div className="w-12 h-1 bg-slate-800 rounded-full mx-auto mb-4" />
          
          {/* Header */}
          <div className="flex justify-between items-start border-b border-slate-900 pb-3 mb-3">
            <div>
              <h3 className="font-extrabold text-slate-100 text-base tracking-wide">{activeDisplayProvince.name}</h3>
              <p className="text-[10px] font-bold text-sky-400 uppercase tracking-widest mt-0.5">
                {activeDisplayProvince.group} • {activeDisplayProvince.region ? activeDisplayProvince.region.split("(")[0].trim() : ""}
              </p>
            </div>
            <button
              onClick={(e) => {
                e.stopPropagation();
                setSelectedProvince(null);
                setHoveredProvince(null);
              }}
              className="p-1.5 rounded-full bg-slate-900 border border-slate-800 text-slate-400 hover:text-white transition-colors cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Content Grid */}
          <div className="grid grid-cols-2 gap-3 mb-3">
            {/* Rainfall Info */}
            <div className="flex items-center gap-3 bg-slate-900/60 p-3 rounded-xl border border-slate-800/80">
              <div className="flex items-center justify-center w-9 h-9 rounded-full bg-sky-500/10 text-sky-400 flex-shrink-0">
                <CloudRain className="w-5 h-5 animate-pulse" />
              </div>
                            <div>
                <p className="text-[9px] text-slate-500 font-mono uppercase tracking-wider">
                  {selectedMode === "realtime" ? "Observed Rain" : (activeHazard === "Wind" ? "Max Wind Gust" : "Forecast Rainfall")}
                </p>
                {activeHazard === "Wind" ? (
                  <p className="text-lg font-black text-white tracking-wide leading-none mt-1">
                    {Math.round(activeDisplayProvince.wind_kph || 0)} <span className="text-[10px] font-medium text-slate-400 font-sans">kph</span>
                  </p>
                ) : (
                  selectedMode === "forecast" && activeDisplayProvince.min_rainfall !== undefined && activeDisplayProvince.max_rainfall !== undefined ? (
                    <p className="text-lg font-black text-white tracking-wide leading-tight mt-1">
                      {Math.round(activeDisplayProvince.min_rainfall)} - {Math.round(activeDisplayProvince.max_rainfall)} <span className="text-[10px] font-medium text-slate-400 font-sans">mm/24h</span>
                      <br /><span className="text-[9px] font-normal text-slate-400 block mt-0.5">Peak Consensus: {Math.round(activeDisplayProvince.rainfall)} mm</span>
                    </p>
                  ) : (
                    <p className="text-lg font-black text-white tracking-wide leading-none mt-1">
                      {Math.round(activeDisplayProvince.rainfall)} <span className="text-[10px] font-medium text-slate-400 font-sans">mm/24h</span>
                    </p>
                  )
                )}
              </div>
            </div>

            {/* Confidence */}
            <div className="bg-slate-900/45 p-3 rounded-xl border border-slate-800/80 text-[10px] font-mono flex flex-col justify-center">
              <div className="flex justify-between items-center text-slate-400">
                <span>Confidence:</span>
                <span className={`font-bold ${
                  activeDisplayProvince.confidence === 'High' ? 'text-emerald-400' :
                  activeDisplayProvince.confidence === 'Medium' ? 'text-yellow-400' : 'text-red-400'
                }`}>{activeDisplayProvince.confidence}</span>
              </div>
              <div className="flex justify-between items-center text-slate-500 text-[9px] mt-1 border-t border-slate-900 pt-1">
                <span>Agreement:</span>
                <span className="font-bold text-slate-300">{activeDisplayProvince.agreement || 0}%</span>
              </div>
            </div>
          </div>

          {/* Model Breakdown */}
          {activeDisplayProvince.models && (
            <div className="bg-slate-900/30 px-3.5 py-2 rounded-lg border border-slate-900 text-[10px] font-mono flex justify-between items-center mb-3">
              <span className="text-slate-500 uppercase tracking-widest text-[8.5px]">Model Consensus:</span>
              <div className="flex gap-3 text-slate-300">
                <span>IFS: <strong className="text-white">{Math.round(activeDisplayProvince.models.IFS)} mm</strong></span>
                <span className="text-slate-700">|</span>
                <span>AIFS: <strong className="text-white">{Math.round(activeDisplayProvince.models.AIFS)} mm</strong></span>
              </div>
            </div>
          )}

          {/* Threat level warning card */}
          {activeDisplayProvince.alert && (
            <div className={`p-3 rounded-xl border text-xs leading-relaxed flex flex-col gap-1.5 ${activeDisplayProvince.alert.style}`}>
              <div className="flex items-center gap-1.5 font-black uppercase tracking-wider text-[10px]">
                <ShieldAlert className="w-4 h-4 flex-shrink-0" />
                <span>{activeDisplayProvince.alert.title}</span>
              </div>
              <p className="opacity-95 font-medium">{activeDisplayProvince.alert.text}</p>
            </div>
          )}
        </div>
      )}

    </div>
  );
};

export default WeatherAdvisory;
