import React, { useState, useEffect, useRef, useMemo } from "react";
import { 
  CloudRain, 
  AlertTriangle, 
  ChevronRight, 
  Info, 
  Compass, 
  Maximize2, 
  Layers, 
  MapPin, 
  TrendingUp, 
  ShieldAlert,
  Smartphone
} from "lucide-react";

const WeatherAdvisory = () => {
  const [geoData, setGeoData] = useState(null);
  const [advisoryData, setAdvisoryData] = useState(null);
  const [activeRegion, setActiveRegion] = useState("All");
  const [hoveredProvince, setHoveredProvince] = useState(null);
  const [tooltipPos, setTooltipPos] = useState({ x: 0, y: 0 });
  const [isTooltipVisible, setIsTooltipVisible] = useState(false);
  const [showLabels, setShowLabels] = useState(false);
  const [showMobileNotice, setShowMobileNotice] = useState(false);
  const mapContainerRef = useRef(null);

  useEffect(() => {
    // Show responsive notice on small screens (< 1024px) if not dismissed today
    if (typeof window !== "undefined" && window.innerWidth < 1024) {
      const todayStr = new Date().toISOString().split('T')[0]; // e.g., '2026-05-29'
      const lastDismissedDate = localStorage.getItem("ph_weather_mobile_notice_dismissed_date");
      if (lastDismissedDate !== todayStr) {
        setShowMobileNotice(true);
      }
    }
  }, []);

  useEffect(() => {
    // Fetch GeoJSON map of provinces (178 KB minimal file downloaded successfully)
    fetch("/data/ph_provinces.json")
      .then((res) => {
        if (!res.ok) throw new Error("Network response was not ok");
        return res.json();
      })
      .then((data) => setGeoData(data))
      .catch((err) => console.error("Failed to load provinces map:", err));

    // Fetch advisory rainfall data generated by generate_advisory_data.py
    fetch("/data/advisory_data.json")
      .then((res) => {
        if (!res.ok) throw new Error("Network response was not ok");
        return res.json();
      })
      .then((data) => setAdvisoryData(data))
      .catch((err) => console.error("Failed to load advisory data:", err));
  }, []);

  const getIslandGroup = (region) => {
    if (!region) return "Luzon";
    const r = region.toLowerCase();
    if (r.includes("visayas")) return "Visayas";
    if (
      r.includes("zamboanga") || 
      r.includes("mindanao") || 
      r.includes("davao") || 
      r.includes("soccsksargen") || 
      r.includes("caraga") || 
      r.includes("bangsamoro") || 
      r.includes("muslim")
    ) {
      return "Mindanao";
    }
    return "Luzon";
  };

  // ── CORE SVG PROJECTION & BOUNDS MAPPING ──
  const mapData = useMemo(() => {
    if (!geoData) return null;

    let minLon = 180, maxLon = -180;
    let minLat = 90, maxLat = -90;

    // Scan coordinates to find strict bounding box limits
    const findBounds = (c) => {
      if (typeof c[0] === 'number') {
        const [lon, lat] = c;
        if (lon < minLon) minLon = lon;
        if (lon > maxLon) maxLon = lon;
        if (lat < minLat) minLat = lat;
        if (lat > maxLat) maxLat = lat;
      } else {
        c.forEach(findBounds);
      }
    };

    geoData.features.forEach((f) => {
      findBounds(f.geometry.coordinates);
    });

    // High-resolution tall aspect ratio canvas
    const canvasWidth = 1000;
    const canvasHeight = 1400;

    // Standard Equirectangular projection mapping to SVG space
    const project = (lon, lat) => {
      const x = ((lon - minLon) / (maxLon - minLon)) * canvasWidth;
      const y = ((maxLat - lat) / (maxLat - minLat)) * canvasHeight;
      return [x, y];
    };

    // Projected feature shapes and centroids
    const projectedFeatures = geoData.features.map((f) => {
      const provName = f.properties.PROV_NAME || f.properties.PROVINCE || f.properties.NAME_1 || f.properties.name || "Unknown";
      const region = f.properties.REGION || "";
      const group = getIslandGroup(region);

      // Recursive path string generator (Polygon / MultiPolygon)
      const generateD = (coords, type) => {
        if (type === "Polygon") {
          return coords.map(ring => {
            return ring.map((coord, index) => {
              const [x, y] = project(coord[0], coord[1]);
              return `${index === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
            }).join(' ') + ' Z';
          }).join(' ');
        } else if (type === "MultiPolygon") {
          return coords.map(poly => {
            return poly.map(ring => {
              return ring.map((coord, index) => {
                const [x, y] = project(coord[0], coord[1]);
                return `${index === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
              }).join(' ') + ' Z';
            }).join(' ');
          }).join(' ');
        }
        return "";
      };

      const d = generateD(f.geometry.coordinates, f.geometry.type);

      // Centroid (average coordinate position)
      let sumX = 0, sumY = 0, count = 0;
      const getCentroid = (c) => {
        if (typeof c[0] === 'number') {
          const [lon, lat] = c;
          const [x, y] = project(lon, lat);
          sumX += x;
          sumY += y;
          count++;
        } else {
          c.forEach(getCentroid);
        }
      };
      getCentroid(f.geometry.coordinates);

      return {
        id: f.properties.ID_1 || provName,
        name: provName,
        region,
        group,
        d,
        centroid: count > 0 ? [sumX / count, sumY / count] : [canvasWidth / 2, canvasHeight / 2]
      };
    });

    // Regional coordinate bounds in SVG canvas space
    const bounds = {
      All: { minX: 0, maxX: canvasWidth, minY: 0, maxY: canvasHeight },
      Luzon: { minX: canvasWidth, maxX: 0, minY: canvasHeight, maxY: 0 },
      Visayas: { minX: canvasWidth, maxX: 0, minY: canvasHeight, maxY: 0 },
      Mindanao: { minX: canvasWidth, maxX: 0, minY: canvasHeight, maxY: 0 }
    };

    // Calculate strict bounding box enclosing each island group
    projectedFeatures.forEach((f) => {
      const g = f.group;
      const originalFeature = geoData.features.find(
        (orig) => 
          (orig.properties.ID_1 || orig.properties.PROV_NAME || orig.properties.PROVINCE || orig.properties.NAME_1) === f.id || 
          orig.properties.PROV_NAME === f.name
      );

      if (originalFeature) {
        const updateBounds = (c) => {
          if (typeof c[0] === 'number') {
            const [lon, lat] = c;
            const [x, y] = project(lon, lat);
            if (x < bounds[g].minX) bounds[g].minX = x;
            if (x > bounds[g].maxX) bounds[g].maxX = x;
            if (y < bounds[g].minY) bounds[g].minY = y;
            if (y > bounds[g].maxY) bounds[g].maxY = y;
          } else {
            c.forEach(updateBounds);
          }
        };
        updateBounds(originalFeature.geometry.coordinates);
      }
    });

    // Apply a robust padding of 8% to prevent clipping at the borders of zoomed regions
    Object.keys(bounds).forEach((key) => {
      if (key === "All") return;
      const b = bounds[key];
      const w = b.maxX - b.minX;
      const h = b.maxY - b.minY;
      const padX = w * 0.08;
      const padY = h * 0.08;

      bounds[key] = {
        minX: Math.max(0, b.minX - padX),
        maxX: Math.min(canvasWidth, b.maxX + padX),
        minY: Math.max(0, b.minY - padY),
        maxY: Math.min(canvasHeight, b.maxY + padY)
      };
    });

    return {
      features: projectedFeatures,
      bounds,
      canvasWidth,
      canvasHeight
    };
  }, [geoData]);

  // Compute active viewBox with coordinates based on zoom selection
  const activeViewBox = useMemo(() => {
    if (!mapData) return "0 0 1000 1400";
    const b = mapData.bounds[activeRegion];
    if (!b) return "0 0 1000 1400";
    const w = b.maxX - b.minX;
    const h = b.maxY - b.minY;
    return `${b.minX.toFixed(1)} ${b.minY.toFixed(1)} ${w.toFixed(1)} ${h.toFixed(1)}`;
  }, [mapData, activeRegion]);

  // Warning metrics summary
  const warningMetrics = useMemo(() => {
    if (!advisoryData || !advisoryData.provinces) return { red: 0, orange: 0, yellow: 0, normal: 0 };
    let red = 0, orange = 0, yellow = 0, normal = 0;
    Object.values(advisoryData.provinces).forEach((p) => {
      const mm = p.rainfall_mm || 0;
      if (mm >= 300) red++;
      else if (mm >= 100) orange++;
      else if (mm >= 50) yellow++;
      else normal++;
    });
    return { red, orange, yellow, normal };
  }, [advisoryData]);

  const handleMouseMove = (e) => {
    if (mapContainerRef.current) {
      const rect = mapContainerRef.current.getBoundingClientRect();
      setTooltipPos({
        x: e.clientX - rect.left + 15,
        y: e.clientY - rect.top + 15,
      });
    }
  };

  const getRainfallColor = (mm) => {
    if (mm >= 300) return "#DC2626"; // Red (Severe)
    if (mm >= 100) return "#F97316"; // Orange (Heavy)
    if (mm >= 50) return "#EAB308";  // Yellow (Moderate)
    return "#334155"; // Default Slate
  };

  const getAlertLevel = (mm) => {
    if (mm >= 300) return { title: "Severe Red Warning", style: "bg-red-500/20 text-red-400 border-red-500/30", text: "Severe flooding and widespread landslides are expected. Move to safe high grounds immediately." };
    if (mm >= 100) return { title: "Heavy Orange Alert", style: "bg-orange-500/20 text-orange-400 border-orange-500/30", text: "Flooding is highly likely. Residents near rivers and hills should prepare to evacuate." };
    if (mm >= 50) return { title: "Moderate Yellow Advisory", style: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30", text: "Localized minor flooding is possible in low-lying and urban areas." };
    return { title: "No Warnings Active", style: "bg-slate-800 text-slate-400 border-slate-700/30", text: "Standard background levels. Scattered light rains possible." };
  };

  // Weather radar/met loading screen
  if (!geoData || !advisoryData) {
    return (
      <div className="flex flex-col items-center justify-center h-[calc(100vh-64px)] w-full bg-slate-950 text-slate-300">
        <div className="relative flex items-center justify-center">
          <div className="absolute w-24 h-24 rounded-full border-2 border-sky-500/25 animate-ping" />
          <div className="absolute w-16 h-16 rounded-full border-2 border-sky-400/40 animate-pulse" />
          <Compass className="w-14 h-14 text-sky-400 animate-spin" style={{ animationDuration: '3s' }} />
        </div>
        <h2 className="mt-8 text-xl font-bold tracking-widest uppercase text-sky-400">Loading Weather Advisories</h2>
        <p className="mt-2 text-xs text-slate-500 font-mono">Loading dynamic province map overlays & ECMWF forecasts...</p>
      </div>
    );
  }

  return (
    <div className="relative h-[calc(100vh-64px)] w-full bg-slate-950 font-sans overflow-hidden flex flex-col md:flex-row">
      
      {/* ── INTERACTIVE DYNAMIC MAP CONTAINER ── */}
      <div 
        ref={mapContainerRef}
        onMouseMove={handleMouseMove}
        className="relative w-full h-[45vh] md:h-full md:flex-1 bg-[#020617] overflow-hidden flex items-center justify-center border-b md:border-b-0 border-slate-800"
      >
        {/* Radar-like background grid lines */}
        <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(ellipse_at_center,rgba(15,23,42,0.6)_0%,rgba(2,6,23,1)_95%)]" />
        
        {/* Dynamic Zooming SVG Map Canvas */}
        {mapData && (
          <svg
            className="w-auto h-full max-h-full max-w-full aspect-[1000/1400] relative z-10 select-none cursor-crosshair transition-all duration-[1200ms] ease-[cubic-bezier(0.2,0.8,0.2,1)]"
            viewBox={activeViewBox}
            style={{ 
              filter: "drop-shadow(0 25px 50px rgba(0, 0, 0, 0.4))",
            }}
          >
            {/* Fine Technical Grid Lines */}
            <defs>
              <pattern id="grid" width="100" height="100" patternUnits="userSpaceOnUse">
                <path d="M 100 0 L 0 0 0 100" fill="none" stroke="rgba(51, 65, 85, 0.15)" strokeWidth="0.8" />
              </pattern>
            </defs>
            <rect width={mapData.canvasWidth} height={mapData.canvasHeight} fill="url(#grid)" />

            {/* Latitude/Longitude tick labels */}
            <g opacity="0.15" className="text-[11px] font-mono fill-slate-500">
              <text x="10" y="20">18.5°N</text>
              <text x="10" y="470">15.0°N</text>
              <text x="10" y="930">10.0°N</text>
              <text x="10" y="1380">5.5°N</text>
              <text x="920" y="1390" textAnchor="end">126.5°E</text>
              <text x="470" y="1390" textAnchor="end">121.5°E</text>
              <text x="50" y="1390" textAnchor="end">117.0°E</text>
            </g>

            {/* Vintage meteorological compass rose */}
            <g transform="translate(90, 135)" className="opacity-[0.25] pointer-events-none font-mono">
              <circle r="48" fill="none" stroke="rgba(255,255,255,0.2)" strokeWidth="1" />
              <circle r="40" fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="0.8" strokeDasharray="2 3" />
              <line x1="0" y1="-55" x2="0" y2="55" stroke="rgba(255,255,255,0.25)" strokeWidth="0.8" />
              <line x1="-55" y1="0" x2="55" y2="0" stroke="rgba(255,255,255,0.25)" strokeWidth="0.8" />
              
              {/* North Arrow Pointer */}
              <polygon points="0,-52 4,-12 0,0 -4,-12" fill="rgba(255,255,255,0.4)" />
              <polygon points="0,52 3,12 0,0 -3,12" fill="rgba(255,255,255,0.15)" />
              <polygon points="52,0 12,3 0,0 12,-3" fill="rgba(255,255,255,0.15)" />
              <polygon points="-52,0 -12,3 0,0 -12,-3" fill="rgba(255,255,255,0.15)" />
              
              <text x="0" y="-60" textAnchor="middle" fill="rgba(255,255,255,0.6)" fontSize="10" fontWeight="bold">N</text>
              <text x="64" y="3" textAnchor="middle" fill="rgba(255,255,255,0.4)" fontSize="8">E</text>
              <text x="0" y="69" textAnchor="middle" fill="rgba(255,255,255,0.4)" fontSize="8">S</text>
              <text x="-64" y="3" textAnchor="middle" fill="rgba(255,255,255,0.4)" fontSize="8">W</text>
            </g>

            {/* Render all 82 Province Paths dynamically */}
            <g>
              {mapData.features.map((feature) => {
                const rainfall = advisoryData.provinces[feature.name]?.rainfall_mm || 0;
                const isHovered = hoveredProvince?.id === feature.id;
                const fill = getRainfallColor(rainfall);

                return (
                  <path
                    key={feature.id}
                    d={feature.d}
                    fill={fill}
                    stroke={isHovered ? "#ffffff" : "rgba(15, 23, 42, 0.4)"}
                    strokeWidth={isHovered ? 2.5 : 0.8}
                    strokeLinejoin="round"
                    className="transition-all duration-300 cursor-pointer"
                    style={{ 
                      opacity: hoveredProvince && !isHovered ? 0.35 : 1,
                      filter: isHovered ? "drop-shadow(0 0 8px rgba(255,255,255,0.4)) brightness(1.15)" : "none"
                    }}
                    onMouseEnter={() => {
                      setHoveredProvince({
                        ...feature,
                        rainfall,
                        alert: getAlertLevel(rainfall)
                      });
                      setIsTooltipVisible(true);
                    }}
                    onMouseLeave={() => {
                      setHoveredProvince(null);
                      setIsTooltipVisible(false);
                    }}
                  />
                );
              })}
            </g>

            {/* Interactive Province Labels (Optionally toggled, or defaults to centroid markers) */}
            <g className="pointer-events-none select-none font-mono">
              {mapData.features.map((feature) => {
                const rainfall = advisoryData.provinces[feature.name]?.rainfall_mm || 0;
                const isHovered = hoveredProvince?.id === feature.id;

                // Only render small high-importance visual guides or toggled text
                if (showLabels && feature.centroid && (rainfall >= 50 || isHovered)) {
                  return (
                    <g key={`lbl-${feature.id}`} transform={`translate(${feature.centroid[0]}, ${feature.centroid[1]})`}>
                      {/* High-visibility label backdrop */}
                      <rect 
                        x={-(feature.name.length * 3.2 + 6)} 
                        y="-15" 
                        width={feature.name.length * 6.4 + 12} 
                        height="18" 
                        rx="4" 
                        fill="rgba(15, 23, 42, 0.85)" 
                        stroke="rgba(255,255,255,0.15)" 
                        strokeWidth="0.5" 
                      />
                      <text
                        y="-3"
                        textAnchor="middle"
                        fill={isHovered ? "#ffffff" : "#cbd5e1"}
                        fontSize="8.5"
                        fontWeight={rainfall >= 100 ? "bold" : "normal"}
                      >
                        {feature.name}
                      </text>
                    </g>
                  );
                }
                return null;
              })}
            </g>
          </svg>
        )}

        {/* Floating Controller overlay */}
        <div className="absolute top-4 left-4 right-4 z-20 flex flex-row md:flex-col items-center md:items-start gap-2.5 flex-wrap pointer-events-none">
          {/* Island Group Selector */}
          <div className="bg-slate-950/80 backdrop-blur-md p-1 rounded-lg border border-slate-800/80 shadow-xl flex gap-1 pointer-events-auto">
            {["All", "Luzon", "Visayas", "Mindanao"].map((region) => (
              <button
                key={region}
                onClick={() => setActiveRegion(region)}
                className={`px-2.5 py-1 rounded-md text-[10px] sm:text-xs font-bold tracking-wide uppercase transition-all duration-300 ${
                  activeRegion === region 
                    ? "bg-sky-500 text-white shadow-md shadow-sky-500/10 scale-105" 
                    : "text-slate-400 hover:text-slate-200 hover:bg-slate-900/50"
                }`}
              >
                {region}
              </button>
            ))}
          </div>

          {/* Toggle Map Labels Label overlay */}
          <button
            onClick={() => setShowLabels(!showLabels)}
            className={`px-2.5 py-1.5 rounded-lg text-[10px] sm:text-xs font-semibold backdrop-blur-md border shadow-lg flex items-center justify-center gap-1.5 pointer-events-auto transition-all duration-300 ${
              showLabels 
                ? "bg-emerald-600/80 text-white border-emerald-500" 
                : "bg-slate-950/80 text-slate-400 border-slate-800 hover:bg-slate-900/80"
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>{showLabels ? "Hide Names" : "Show Names"}</span>
          </button>
        </div>

        {/* Map Bounding Indicators */}
        <div className="absolute bottom-6 left-6 z-20 pointer-events-none select-none flex flex-col gap-1 font-mono text-[10px] text-slate-500 bg-slate-950/60 backdrop-blur-sm px-3 py-2 rounded-lg border border-slate-900/50 shadow-md">
          <div className="flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
            <span className="text-slate-400 font-semibold uppercase tracking-wider">Met-System Online</span>
          </div>
          <div>Scale: 1:1,850,000</div>
          <div>Projection: Equirectangular (WGS84)</div>
          <div className="text-[9px] text-slate-600">Active Zoom: Region {activeRegion}</div>
        </div>

        {/* ── DYNAMIC CURSOR FLOATING GLASS TOOLTIP (DESKTOP ONLY) ── */}
        {isTooltipVisible && hoveredProvince && (
          <div
            className="hidden md:flex absolute z-50 pointer-events-none w-72 rounded-xl border border-slate-700/60 bg-slate-950/90 p-4 text-slate-200 shadow-2xl backdrop-blur-lg transition-opacity duration-200 flex flex-col gap-2.5"
            style={{
              left: tooltipPos.x,
              top: tooltipPos.y,
              transform: "translate3d(0, 0, 0)"
            }}
          >
            {/* Tooltip Header */}
            <div className="flex justify-between items-start border-b border-slate-800 pb-2">
              <div>
                <h3 className="font-bold text-slate-100 text-sm tracking-wide">{hoveredProvince.name}</h3>
                <p className="text-[10px] font-semibold text-sky-400 uppercase tracking-wider mt-0.5">
                  {hoveredProvince.group} • {hoveredProvince.region.split("(")[0].trim()}
                </p>
              </div>
              <MapPin className="w-4 h-4 text-sky-400 opacity-80" />
            </div>

            {/* Precipitation reading metrics */}
            <div className="flex items-center gap-4 bg-slate-900/60 px-3 py-2 rounded-lg border border-slate-800">
              <div className="flex items-center justify-center w-8 h-8 rounded-full bg-sky-500/10 text-sky-400">
                <CloudRain className="w-4 h-4 animate-pulse" />
              </div>
              <div>
                <p className="text-[10px] text-slate-500 font-mono uppercase tracking-wider">Forecast Rainfall</p>
                <p className="text-base font-bold text-white tracking-wide">
                  {hoveredProvince.rainfall} <span className="text-xs font-normal text-slate-400">mm / 24h</span>
                </p>
              </div>
            </div>

            {/* Custom localized advisory actions */}
            <div className={`p-2.5 rounded-lg border text-xs leading-relaxed flex flex-col gap-1 ${hoveredProvince.alert.style}`}>
              <div className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-[10px]">
                <ShieldAlert className="w-3.5 h-3.5" />
                <span>{hoveredProvince.alert.title}</span>
              </div>
              <p className="opacity-90">{hoveredProvince.alert.text}</p>
            </div>
          </div>
        )}

        {/* ── MOBILE SLIDE-UP GLASS BOTTOM-SHEET PANEL ── */}
        {hoveredProvince && (
          <div className="absolute bottom-4 left-4 right-4 z-30 md:hidden pointer-events-auto rounded-xl border border-slate-700/60 bg-slate-950/95 p-3.5 shadow-2xl backdrop-blur-lg flex flex-col gap-2.5 animate-in fade-in slide-in-from-bottom-5 duration-300">
            <div className="flex justify-between items-start">
              <div>
                <h3 className="font-bold text-slate-100 text-sm tracking-wide">{hoveredProvince.name}</h3>
                <p className="text-[10px] font-semibold text-sky-400 uppercase tracking-wider mt-0.5">
                  {hoveredProvince.group} • {hoveredProvince.region.split("(")[0].trim()}
                </p>
              </div>
              <MapPin className="w-4 h-4 text-sky-400 opacity-80" />
            </div>

            <div className="flex items-center justify-between gap-4 bg-slate-900/60 px-3 py-1.5 rounded-lg border border-slate-800">
              <div className="flex items-center gap-2">
                <CloudRain className="w-3.5 h-3.5 text-sky-400 animate-pulse" />
                <span className="text-[10px] text-slate-400 uppercase tracking-wider font-mono">Rainfall:</span>
              </div>
              <p className="text-sm font-bold text-white tracking-wide">
                {hoveredProvince.rainfall} <span className="text-[10px] font-normal text-slate-400">mm / 24h</span>
              </p>
            </div>

            <div className={`p-2 rounded-lg border text-[11px] leading-snug flex items-center gap-2 ${hoveredProvince.alert.style}`}>
              <ShieldAlert className="w-4 h-4 flex-shrink-0" />
              <p className="opacity-95">{hoveredProvince.alert.text}</p>
            </div>
          </div>
        )}

      </div>

      {/* ── SIDEBAR PANEL (PAGASA WEATHER ALERT DESK STYLE) ── */}
      <div className="w-full md:w-80 lg:w-96 flex-1 md:flex-none bg-[#090d16]/95 md:bg-[#050811]/90 backdrop-blur-xl border-t md:border-t-0 md:border-l border-slate-800/80 flex flex-col z-20 overflow-hidden shadow-[-15px_0_35px_rgba(0,0,0,0.6)]">
        
        {/* PAGASA Style Header */}
        <div className="bg-gradient-to-r from-sky-950/80 to-blue-950/80 p-5 border-b border-sky-800/40 text-center relative overflow-hidden flex-shrink-0">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(14,165,233,0.1)_0%,transparent_70%)] pointer-events-none" />
          <h1 className="text-lg font-black tracking-widest text-white uppercase flex items-center justify-center gap-2">
            <ShieldAlert className="w-5 h-5 text-sky-400" />
            <span>Rainfall Forecast</span>
          </h1>
          <p className="text-xs font-semibold text-sky-300 uppercase tracking-widest mt-1">24-Hour Advisory Bulletin</p>
          {advisoryData && (
            <div className="mt-3 flex flex-col gap-1.5 items-center">
              <span className="text-[10px] text-slate-300 font-mono bg-slate-950/70 py-1 px-3 rounded-full border border-slate-800/60 w-fit">
                {advisoryData.validity}
              </span>
              <span className="text-[9px] text-slate-400 font-mono uppercase tracking-wider">
                Model Run: {advisoryData.init_time}
              </span>
            </div>
          )}
        </div>

        {/* Model Forecast Context Card */}
        <div className="p-4 bg-slate-950/50 border-b border-slate-900 flex flex-col gap-3 flex-shrink-0">
          <div>
            <div className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">Model Forecast:</div>
            <div className="text-sm font-bold text-sky-400 mt-0.5">{advisoryData.system}</div>
          </div>
        </div>

        {/* Advisory Action Tables */}
        <div className="p-5 flex-1 overflow-y-auto space-y-5">
          <h2 className="text-slate-400 font-bold uppercase tracking-wider text-[11px] flex items-center gap-1.5 border-b border-slate-800/80 pb-2 mb-4">
            <TrendingUp className="w-3.5 h-3.5 text-sky-400" />
            <span>Threat Warning Categories</span>
          </h2>
          
          {/* Red Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-red-950 shadow-lg group transition-all duration-300 hover:border-red-900/60">
            <div className="bg-gradient-to-r from-red-700 to-red-600 px-4 py-2 flex justify-between items-center text-white text-xs font-bold tracking-widest uppercase">
              <span>Red Level (300+ mm)</span>
              {warningMetrics.red > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-red-950/80 text-[10px] text-red-100 animate-pulse border border-red-700">
                  {warningMetrics.red} Provinces
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-red-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Extreme, catastrophic flooding expected in highly vulnerable areas and low plains.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-red-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Landslides:</strong> Extreme, widespread landslides are highly likely in high-slope mountain zones.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-red-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Evacuate hazard-exposed residences. Seek high shelter immediately.</p>
              </div>
            </div>
          </div>

          {/* Orange Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-orange-950 shadow-lg group transition-all duration-300 hover:border-orange-900/60">
            <div className="bg-gradient-to-r from-orange-600 to-orange-500 px-4 py-2 flex justify-between items-center text-white text-xs font-bold tracking-widest uppercase">
              <span>Orange Level (100-200 mm)</span>
              {warningMetrics.orange > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-orange-950/80 text-[10px] text-orange-200 border border-orange-700">
                  {warningMetrics.orange} Provinces
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-orange-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Severe widespread urban and lowland flooding near water channels.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-orange-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Landslides:</strong> Heavy soil saturations likely to cause slides in moderate risk mountains.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-orange-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Prepare grab-bags and emergency supplies. Be on standby alert to evacuate.</p>
              </div>
            </div>
          </div>

          {/* Yellow Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-yellow-950 shadow-lg group transition-all duration-300 hover:border-yellow-900/60">
            <div className="bg-gradient-to-r from-yellow-500 to-yellow-400 px-4 py-2 flex justify-between items-center text-slate-900 text-xs font-extrabold tracking-widest uppercase">
              <span>Yellow Level (50-100 mm)</span>
              {warningMetrics.yellow > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-yellow-950/85 text-[10px] text-yellow-900 border border-yellow-400 font-bold">
                  {warningMetrics.yellow} Provinces
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Light localized pooling in highly urbanized street sectors.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Landslides:</strong> Isolated, small mud slips possible near mountain cuts.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Stay tuned to warnings. Clear yard debris and monitor channel flows.</p>
              </div>
            </div>
          </div>
          
        </div>

        {/* Meteorological Footer info */}
        {advisoryData && (
          <div className="bg-slate-950 p-4 border-t border-slate-900 flex flex-col gap-2 relative flex-shrink-0">
            <div className="text-emerald-400 font-bold text-xs text-center tracking-wide uppercase">
              {advisoryData.title}
            </div>
            <div className="flex items-center justify-center gap-3 mt-1 pb-1">
              <img src="/images/logo.png" alt="Logo" className="h-7 w-7 opacity-85 object-contain" />
              <div className="text-[9px] text-slate-500 font-mono leading-tight">
                ECMWF IFS High Resolution Model<br/>
                Weather Analysis & Forecasting Desk
              </div>
            </div>
          </div>
        )}

      </div>

      {/* ── RESPONSIVE MOBILE DISPLAY ADVISORY MODAL ── */}
      {showMobileNotice && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center p-5 bg-slate-950/80 backdrop-blur-lg animate-in fade-in duration-300">
          <div className="relative max-w-md w-full bg-[#080d19]/95 border border-slate-800/80 rounded-2xl p-6 text-center shadow-2xl flex flex-col items-center gap-5 animate-in zoom-in-95 duration-300">
            {/* Glowing Smartphone Alert Icon */}
            <div className="relative flex items-center justify-center w-16 h-16 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20">
              <Smartphone className="w-8 h-8" />
              <span className="absolute inset-0 rounded-full border border-amber-500/30 animate-ping" style={{ animationDuration: '2s' }} />
            </div>

            {/* Warning Message Content */}
            <div className="space-y-2">
              <h2 className="text-lg font-extrabold tracking-wide text-slate-100 uppercase">Screen Size Notice</h2>
              <p className="text-xs text-slate-400 leading-relaxed pt-1.5 font-semibold text-amber-300">
                This page is not optimized for small screens.
              </p>
              <p className="text-xs text-slate-400 leading-relaxed">
                You can still access this page but it may not perform well; we suggest that you go to a desktop site.
              </p>
              <p className="text-[11px] font-bold text-sky-400 pt-1 font-mono">
                Thank you for your understanding!
              </p>
            </div>

            {/* OK Got It Action Button */}
            <button
              onClick={() => {
                setShowMobileNotice(false);
                if (typeof window !== "undefined") {
                  const todayStr = new Date().toISOString().split('T')[0];
                  localStorage.setItem("ph_weather_mobile_notice_dismissed_date", todayStr);
                }
              }}
              className="w-full mt-2 py-3 rounded-xl bg-sky-500 hover:bg-sky-600 active:scale-[0.98] text-white text-xs font-bold uppercase tracking-wider shadow-lg shadow-sky-500/25 transition-all duration-200 pointer-events-auto"
            >
              Understand & Proceed
            </button>
          </div>
        </div>
      )}

    </div>
  );
};

export default WeatherAdvisory;
