import React, { useState, useEffect, useRef, useMemo } from "react";
import {
  CloudRain,
  AlertTriangle,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Info,
  Compass,
  Maximize2,
  Layers,
  MapPin,
  TrendingUp,
  ShieldAlert,
  Smartphone,
  Download
} from "lucide-react";

const WeatherAdvisory = () => {
  const [geoData, setGeoData] = useState(null);
  const [advisoryData, setAdvisoryData] = useState(null);
  const [dataSource, setDataSource] = useState("forecast");
  const [observedWindow, setObservedWindow] = useState("1h");
  const [activeRegion, setActiveRegion] = useState("All");

  const activeAdvisory = useMemo(() => {
    if (!advisoryData) return null;
    if (dataSource === "observed" && advisoryData.observed) {
      const windows = advisoryData.observed.windows || {};
      return windows[observedWindow] || advisoryData.observed;
    }
    return advisoryData.forecast || {
      title: advisoryData.title,
      validity: advisoryData.validity,
      system: advisoryData.system,
      init_time: advisoryData.init_time,
      provinces: advisoryData.provinces
    };
  }, [advisoryData, dataSource, observedWindow]);

  const activeThresholds = useMemo(() => {
    if (dataSource === "forecast") {
      return { red: 200, orange: 100, yellow: 50, lightBlue: 25, gray: 0.1 };
    }
    switch (observedWindow) {
      case "1h":
        return { purple: 50, red: 20, orange: 10, yellow: 5, lightBlue: 2.6, gray: 0.1 };
      case "3h":
        return { red: 50, orange: 30, yellow: 15, lightBlue: 7, gray: 0.1 };
      case "6h":
        return { red: 80, orange: 50, yellow: 25, lightBlue: 12, gray: 0.1 };
      case "12h":
        return { red: 130, orange: 80, yellow: 40, lightBlue: 20, gray: 0.1 };
      case "24h":
      default:
        return { red: 200, orange: 100, yellow: 50, lightBlue: 25, gray: 0.1 };
    }
  }, [dataSource, observedWindow]);

  const getLevelMeaning = (level, window, isObserved) => {
    if (!isObserved) return null;
    if (level === "red") {
      if (window === "1h") return "Severe Red (20-50 mm) / Extreme Purple (>50 mm)";
      if (window === "3h") return "Extreme / Torrential (>50 mm)";
      if (window === "6h") return "Extreme (>80 mm) - High flood potential";
      if (window === "12h") return "Severe (>130 mm)";
    }
    if (level === "lightBlue") {
      if (window === "1h") return "Light Blue (2.6-5 mm)";
      if (window === "3h") return "Light Blue (7-15 mm)";
      if (window === "6h") return "Light rain (12-25 mm)";
      if (window === "12h") return "Light Blue (20-40 mm)";
    }
    if (level === "gray") {
      if (window === "1h") return "Trace / Light rain (0.1-2.5 mm)";
      if (window === "3h") return "Trace / Light rain (0.1-7 mm)";
      if (window === "6h") return "Trace / Light rain (0.1-12 mm)";
      if (window === "12h") return "Trace / Light rain (0.1-20 mm)";
    }
    return null;
  };

  const formatRainfall = (val) => {
    if (val === 0) return "0";
    if (val % 1 === 0) return val.toString();
    return val.toFixed(1);
  };
  const [hoveredProvince, setHoveredProvince] = useState(null);
  const [tooltipPos, setTooltipPos] = useState({ x: 0, y: 0 });
  const [isTooltipVisible, setIsTooltipVisible] = useState(false);
  const [showLabels, setShowLabels] = useState(false);
  const [showMobileNotice, setShowMobileNotice] = useState(false);
  const [isMobileCollapsed, setIsMobileCollapsed] = useState(true);
  const mapContainerRef = useRef(null);

  useEffect(() => {
    // Show responsive notice on small screens (< 1024px) if not dismissed today
    if (typeof window !== "undefined" && window.innerWidth < 1024) {
      const todayStr = new Date().toISOString().split('T')[0]; // e.g., '2026-05-29'
      const lastDismissedDate = localStorage.getItem("ph_weather_mobile_notice_dismissed_date");
      if (lastDismissedDate !== todayStr) {
        setShowMobileNotice(true);
      }
    }
  }, []);

  useEffect(() => {
    // Fetch GeoJSON map of provinces (178 KB minimal file downloaded successfully)
    fetch("/data/ph_provinces.json")
      .then((res) => {
        if (!res.ok) throw new Error("Network response was not ok");
        return res.json();
      })
      .then((data) => setGeoData(data))
      .catch((err) => console.error("Failed to load provinces map:", err));

    // Fetch forecast advisory data generated by generate_advisory_data.py
    fetch("/data/advisory_data.json")
      .then((res) => {
        if (!res.ok) throw new Error("Network response was not ok");
        return res.json();
      })
      .then((data) => {
        setAdvisoryData((prev) => ({
          ...(prev || {}),
          forecast: data.forecast || data
        }));
      })
      .catch((err) => console.error("Failed to load advisory forecast data:", err));

    // Fetch observed JAXA data from edge-cached Vercel API
    fetch("/api/jaxa")
      .then((res) => {
        if (!res.ok) throw new Error("Network response was not ok");
        return res.json();
      })
      .then((data) => {
        setAdvisoryData((prev) => ({
          ...(prev || {}),
          observed: data
        }));
      })
      .catch((err) => console.error("Failed to load JAXA observed data:", err));
  }, []);

  const exportMapAsPNG = () => {
    const svgElement = mapContainerRef.current?.querySelector("svg");
    if (!svgElement || !activeAdvisory) return;

    try {
      // 1. Compile the lists of provinces under each category dynamically
      const redProvinces = [];
      const orangeProvinces = [];
      const yellowProvinces = [];
      const lightBlueProvinces = [];
      const grayProvinces = [];

      Object.entries(activeAdvisory.provinces).forEach(([name, p]) => {
        const mm = p.rainfall_mm || 0;
        if (mm >= activeThresholds.red) redProvinces.push(name);
        else if (mm >= activeThresholds.orange) orangeProvinces.push(name);
        else if (mm >= activeThresholds.yellow) yellowProvinces.push(name);
        else if (mm >= activeThresholds.lightBlue) lightBlueProvinces.push(name);
        else if (activeThresholds.gray && mm >= activeThresholds.gray) grayProvinces.push(name);
      });

      redProvinces.sort();
      orangeProvinces.sort();
      yellowProvinces.sort();
      lightBlueProvinces.sort();
      grayProvinces.sort();

      // Helper function to render a clean vertical list of province names
      const renderProvinceList = (provinces, xPos, startY, color, checkPurple = false) => {
        if (provinces.length === 0) {
          return `<text x="${xPos}" y="${startY}" fill="#475569" font-size="9.5" text-anchor="middle" font-style="italic">None</text>`;
        }

        let markup = "";
        const maxLines = 10; // Allow up to 10 provinces listed in the expanded card space
        for (let i = 0; i < provinces.length; i++) {
          if (i >= maxLines) {
            markup += `<text x="${xPos}" y="${startY + i * 11.5}" fill="${color}" font-size="8.5" font-weight="bold" text-anchor="middle">+ ${provinces.length - maxLines} more</text>`;
            break;
          }
          let itemColor = "#e2e8f0";
          if (checkPurple) {
            const mm = activeAdvisory.provinces[provinces[i]]?.rainfall_mm || 0;
            if (activeThresholds.purple && mm >= activeThresholds.purple) {
              itemColor = "#d946ef"; // Fuchsia-500
            }
          }
          markup += `<text x="${xPos}" y="${startY + i * 11.5}" fill="${itemColor}" font-size="9" text-anchor="middle">${provinces[i]}</text>`;
        }
        return markup;
      };

      // Clone the SVG so we can force a full 1400x1400 canvas without affecting on-screen zoom state
      const clonedSvg = svgElement.cloneNode(true);
      clonedSvg.setAttribute("viewBox", "0 0 1400 1400");
      clonedSvg.setAttribute("width", "1400");
      clonedSvg.setAttribute("height", "1400");
      clonedSvg.removeAttribute("style");

      // Dynamic Title, Legend, and Metrics injection programmatically (so they only appear on the saved image)
      const svgNS = "http://www.w3.org/2000/svg";

      // 1. Dynamic Map Title Block (Scaled Up for High Readability)
      const titleGroup = document.createElementNS(svgNS, "g");
      titleGroup.setAttribute("transform", "translate(1010, 60)");
      titleGroup.setAttribute("font-family", "monospace");

      const titleText = dataSource === "forecast" ? "24-HOUR RAINFALL FORECAST" : `${observedWindow.toUpperCase()} OBSERVED RAINFALL`;
      const windowLabel = dataSource === "forecast" ? "FORECAST VALIDITY WINDOW:" : "OBSERVATION TIME RANGE:";
      const runLabel = dataSource === "forecast" ? "Model Run:" : "Data Window:";
      const validityParts = activeAdvisory.validity.split(" to ");
      const validityStart = validityParts[0] || "";
      const validityEnd = validityParts[1] || "";

      titleGroup.innerHTML = `
        <rect x="0" y="0" width="370" height="240" rx="14" fill="rgba(9, 13, 22, 0.9)" stroke="rgba(255, 255, 255, 0.15)" stroke-width="1.2" />
        <text x="25" y="40" fill="#38bdf8" font-size="14" font-weight="bold" letter-spacing="1.2">${titleText}</text>
        <text x="25" y="65" fill="#f1f5f9" font-size="13" font-weight="bold" font-family="sans-serif">${activeAdvisory.system}</text>
        <line x1="25" y1="80" x2="345" y2="80" stroke="rgba(255, 255, 255, 0.12)" stroke-width="1" />
        <text x="25" y="108" fill="#e2e8f0" font-size="11" font-weight="bold" font-family="sans-serif">${windowLabel}</text>
        <text x="25" y="132" fill="#38bdf8" font-size="11.5" font-weight="bold">${validityStart}</text>
        <text x="25" y="152" fill="#64748b" font-size="10.5" font-weight="bold">to</text>
        <text x="25" y="172" fill="#38bdf8" font-size="11.5" font-weight="bold">${validityEnd}</text>
        <line x1="25" y1="192" x2="345" y2="192" stroke="rgba(255, 255, 255, 0.08)" stroke-width="1" />
        <text x="25" y="215" fill="#64748b" font-size="10.5">${runLabel} ${activeAdvisory.init_time}</text>
      `;
      clonedSvg.appendChild(titleGroup);

      const legendItems = [];
      if (activeThresholds.purple) {
        legendItems.push({
          color: "#701A75",
          title: `Purple Warning (${activeThresholds.purple}+ mm)`,
          desc: "Extreme torrential rainfall & catastrophic danger"
        });
      }
      legendItems.push({
        color: "#DC2626",
        title: activeThresholds.purple 
          ? `Red Warning (${activeThresholds.red} - ${activeThresholds.purple} mm)` 
          : `Red Warning (${activeThresholds.red}+ mm)`,
        desc: dataSource === "observed" && observedWindow === "3h"
          ? "Extreme / Torrential rainfall"
          : dataSource === "observed" && observedWindow === "6h"
            ? "Extreme (high flood potential)"
            : "Severe widespread flooding & landslides"
      });
      legendItems.push({
        color: "#F97316",
        title: `Orange Alert (${activeThresholds.orange} - ${activeThresholds.red} mm)`,
        desc: "High risk of flooding & landslides"
      });
      legendItems.push({
        color: "#EAB308",
        title: `Yellow Advisory (${activeThresholds.yellow} - ${activeThresholds.orange} mm)`,
        desc: "Localized pooling & minor flooding"
      });
      legendItems.push({
        color: "#38BDF8",
        title: `Light Blue Alert (${activeThresholds.lightBlue} - ${activeThresholds.yellow} mm)`,
        desc: dataSource === "observed" && observedWindow === "6h" ? "Light rain" : "Localized minor ponding & wet roads"
      });
      if (activeThresholds.gray) {
        legendItems.push({
          color: "#64748B",
          title: `Gray Alert (${activeThresholds.gray} - ${activeThresholds.lightBlue} mm)`,
          desc: "Trace to light rain, low warning risk"
        });
      }
      legendItems.push({
        color: "#334155",
        title: `Light / No Warning (< ${activeThresholds.gray || activeThresholds.lightBlue} mm)`,
        desc: "Isolated light rains or clear skies"
      });

      const itemHeight = 52;
      const legendHeight = 70 + legendItems.length * itemHeight;

      // 2. Warning Level Legend Box (Scaled Up for High Readability)
      const legendGroup = document.createElementNS(svgNS, "g");
      legendGroup.setAttribute("transform", "translate(1010, 320)");
      legendGroup.setAttribute("font-family", "sans-serif");
      
      let legendContent = `
        <rect x="0" y="0" width="370" height="${legendHeight}" rx="14" fill="rgba(9, 13, 22, 0.9)" stroke="rgba(255, 255, 255, 0.15)" stroke-width="1.2" />
        <text x="25" y="38" fill="#38bdf8" font-size="13" font-weight="bold" letter-spacing="1.5" font-family="monospace">WARNING LEVEL LEGEND</text>
        <line x1="25" y1="50" x2="345" y2="50" stroke="rgba(255, 255, 255, 0.12)" stroke-width="1" />
      `;

      legendItems.forEach((item, index) => {
        const yPos = 68 + index * itemHeight;
        legendContent += `
          <rect x="25" y="${yPos}" width="24" height="24" rx="6" fill="${item.color}" stroke="rgba(255, 255, 255, 0.2)" stroke-width="0.5" />
          <text x="62" y="${yPos + 16}" fill="#f1f5f9" font-size="12" font-weight="bold">${item.title}</text>
          <text x="62" y="${yPos + 31}" fill="#94a3b8" font-size="10">${item.desc}</text>
        `;
      });
      legendGroup.innerHTML = legendContent;
      clonedSvg.appendChild(legendGroup);

      // 3. Warning Metrics Summary Box (Scaled Up and Expanded to List Province Names)
      const metricsGroup = document.createElementNS(svgNS, "g");
      const metricsY = 340 + legendHeight;
      metricsGroup.setAttribute("transform", `translate(1010, ${metricsY})`);
      metricsGroup.setAttribute("font-family", "sans-serif");

      const columns = [];
      const numCols = activeThresholds.gray ? 5 : 4;
      const colWidth = numCols === 5 ? 62 : 76;
      const colGap = 5;
      const colStartX = numCols === 5 ? 20 : 25;

      const redListMarkup = renderProvinceList(redProvinces, colWidth / 2, 92, "#ef4444", true);
      const orangeListMarkup = renderProvinceList(orangeProvinces, colWidth / 2, 92, "#fb923c");
      const yellowListMarkup = renderProvinceList(yellowProvinces, colWidth / 2, 92, "#facc15");
      const lightBlueListMarkup = renderProvinceList(lightBlueProvinces, colWidth / 2, 92, "#38bdf8");
      const grayListMarkup = activeThresholds.gray 
        ? renderProvinceList(grayProvinces, colWidth / 2, 92, "#cbd5e1") 
        : "";

      columns.push({
        color: "#DC2626",
        bgColor: "rgba(220, 38, 38, 0.12)",
        strokeColor: "rgba(220, 38, 38, 0.25)",
        title: activeThresholds.purple ? "RED/PURP" : "RED",
        count: warningMetrics.red,
        listMarkup: redListMarkup
      });
      columns.push({
        color: "#F97316",
        bgColor: "rgba(249, 115, 22, 0.12)",
        strokeColor: "rgba(249, 115, 22, 0.25)",
        title: "ORANGE",
        count: warningMetrics.orange,
        listMarkup: orangeListMarkup
      });
      columns.push({
        color: "#EAB308",
        bgColor: "rgba(234, 179, 8, 0.12)",
        strokeColor: "rgba(234, 179, 8, 0.25)",
        title: "YELLOW",
        count: warningMetrics.yellow,
        listMarkup: yellowListMarkup
      });
      columns.push({
        color: "#38BDF8",
        bgColor: "rgba(56, 189, 248, 0.12)",
        strokeColor: "rgba(56, 189, 248, 0.25)",
        title: "LT BLUE",
        count: warningMetrics.lightBlue,
        listMarkup: lightBlueListMarkup
      });
      if (activeThresholds.gray) {
        columns.push({
          color: "#94A3B8",
          bgColor: "rgba(148, 163, 184, 0.12)",
          strokeColor: "rgba(148, 163, 184, 0.25)",
          title: "GRAY",
          count: warningMetrics.gray,
          listMarkup: grayListMarkup
        });
      }

      let columnsMarkup = "";
      columns.forEach((col, index) => {
        const xPos = colStartX + index * (colWidth + colGap);
        columnsMarkup += `
          <g transform="translate(${xPos}, 0)">
            <rect x="0" y="0" width="${colWidth}" height="65" rx="10" fill="${col.bgColor}" stroke="${col.strokeColor}" stroke-width="1" />
            <text x="${colWidth / 2}" y="35" fill="${col.color}" font-size="24" font-weight="bold" text-anchor="middle">${col.count}</text>
            <text x="${colWidth / 2}" y="52" fill="${col.color}" font-size="8.5" font-weight="bold" text-anchor="middle" letter-spacing="0.5">${col.title}</text>
            <line x1="8" y1="78" x2="${colWidth - 8}" y2="78" stroke="rgba(255, 255, 255, 0.08)" stroke-width="0.8" />
            ${col.listMarkup}
          </g>
        `;
      });

      metricsGroup.innerHTML = `
        <rect x="0" y="0" width="370" height="290" rx="14" fill="rgba(9, 13, 22, 0.9)" stroke="rgba(255, 255, 255, 0.15)" stroke-width="1.2" />
        <text x="25" y="38" fill="#38bdf8" font-size="13" font-weight="bold" letter-spacing="1.5" font-family="monospace">PROVINCIAL WARNING METRICS</text>
        <line x1="25" y1="50" x2="345" y2="50" stroke="rgba(255, 255, 255, 0.12)" stroke-width="1" />
        
        <g transform="translate(0, 70)">
          ${columnsMarkup}
        </g>
      `;
      clonedSvg.appendChild(metricsGroup);

      const serializer = new XMLSerializer();
      let svgString = serializer.serializeToString(clonedSvg);

      const svgBlob = new Blob([svgString], { type: "image/svg+xml;charset=utf-8" });
      const URL = window.URL || window.webkitURL || window;
      const blobURL = URL.createObjectURL(svgBlob);

      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement("canvas");
        canvas.width = 1400;
        canvas.height = 1400;
        const ctx = canvas.getContext("2d");

        // Premium deep dark slate canvas background
        ctx.fillStyle = "#020617";
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

        const pngURL = canvas.toDataURL("image/png");
        const downloadLink = document.createElement("a");
        downloadLink.href = pngURL;
        const filePrefix = dataSource === "forecast" ? "Forecast" : "Observed";
        downloadLink.download = `PH_Weather_Advisory_${filePrefix}_${new Date().toISOString().split('T')[0]}.png`;
        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);

        URL.revokeObjectURL(blobURL);
      };

      img.src = blobURL;
    } catch (err) {
      console.error("Failed to export SVG map as PNG:", err);
    }
  };

  const getIslandGroup = (region) => {
    if (!region) return "Luzon";
    const r = region.toLowerCase();
    if (r.includes("visayas")) return "Visayas";
    if (
      r.includes("zamboanga") ||
      r.includes("mindanao") ||
      r.includes("davao") ||
      r.includes("soccsksargen") ||
      r.includes("caraga") ||
      r.includes("bangsamoro") ||
      r.includes("muslim")
    ) {
      return "Mindanao";
    }
    return "Luzon";
  };

  // ── CORE SVG PROJECTION & BOUNDS MAPPING ──
  const mapData = useMemo(() => {
    if (!geoData) return null;

    let minLon = 180, maxLon = -180;
    let minLat = 90, maxLat = -90;

    // Scan coordinates to find strict bounding box limits
    const findBounds = (c) => {
      if (typeof c[0] === 'number') {
        const [lon, lat] = c;
        if (lon < minLon) minLon = lon;
        if (lon > maxLon) maxLon = lon;
        if (lat < minLat) minLat = lat;
        if (lat > maxLat) maxLat = lat;
      } else {
        c.forEach(findBounds);
      }
    };

    geoData.features.forEach((f) => {
      findBounds(f.geometry.coordinates);
    });

    // High-resolution tall aspect ratio canvas
    const canvasWidth = 1000;
    const canvasHeight = 1400;

    // Standard Equirectangular projection mapping to SVG space
    const project = (lon, lat) => {
      const x = ((lon - minLon) / (maxLon - minLon)) * canvasWidth;
      const y = ((maxLat - lat) / (maxLat - minLat)) * canvasHeight;
      return [x, y];
    };

    // Projected feature shapes and centroids
    const projectedFeatures = geoData.features.map((f) => {
      const provName = f.properties.PROV_NAME || f.properties.PROVINCE || f.properties.NAME_1 || f.properties.name || "Unknown";
      const region = f.properties.REGION || "";
      const group = getIslandGroup(region);

      // Recursive path string generator (Polygon / MultiPolygon)
      const generateD = (coords, type) => {
        if (type === "Polygon") {
          return coords.map(ring => {
            return ring.map((coord, index) => {
              const [x, y] = project(coord[0], coord[1]);
              return `${index === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
            }).join(' ') + ' Z';
          }).join(' ');
        } else if (type === "MultiPolygon") {
          return coords.map(poly => {
            return poly.map(ring => {
              return ring.map((coord, index) => {
                const [x, y] = project(coord[0], coord[1]);
                return `${index === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
              }).join(' ') + ' Z';
            }).join(' ');
          }).join(' ');
        }
        return "";
      };

      const d = generateD(f.geometry.coordinates, f.geometry.type);

      // Centroid (average coordinate position)
      let sumX = 0, sumY = 0, count = 0;
      const getCentroid = (c) => {
        if (typeof c[0] === 'number') {
          const [lon, lat] = c;
          const [x, y] = project(lon, lat);
          sumX += x;
          sumY += y;
          count++;
        } else {
          c.forEach(getCentroid);
        }
      };
      getCentroid(f.geometry.coordinates);

      return {
        id: f.properties.ID_1 || provName,
        name: provName,
        region,
        group,
        d,
        centroid: count > 0 ? [sumX / count, sumY / count] : [canvasWidth / 2, canvasHeight / 2]
      };
    });

    // Regional coordinate bounds in SVG canvas space (kept to 1000px wide for screen, only PNG export expands to 1400px)
    const bounds = {
      All: { minX: 0, maxX: 1000, minY: 0, maxY: canvasHeight },
      Luzon: { minX: canvasWidth, maxX: 0, minY: canvasHeight, maxY: 0 },
      Visayas: { minX: canvasWidth, maxX: 0, minY: canvasHeight, maxY: 0 },
      Mindanao: { minX: canvasWidth, maxX: 0, minY: canvasHeight, maxY: 0 }
    };

    // Calculate strict bounding box enclosing each island group
    projectedFeatures.forEach((f) => {
      const g = f.group;
      const originalFeature = geoData.features.find(
        (orig) =>
          (orig.properties.ID_1 || orig.properties.PROV_NAME || orig.properties.PROVINCE || orig.properties.NAME_1) === f.id ||
          orig.properties.PROV_NAME === f.name
      );

      if (originalFeature) {
        const updateBounds = (c) => {
          if (typeof c[0] === 'number') {
            const [lon, lat] = c;
            const [x, y] = project(lon, lat);
            if (x < bounds[g].minX) bounds[g].minX = x;
            if (x > bounds[g].maxX) bounds[g].maxX = x;
            if (y < bounds[g].minY) bounds[g].minY = y;
            if (y > bounds[g].maxY) bounds[g].maxY = y;
          } else {
            c.forEach(updateBounds);
          }
        };
        updateBounds(originalFeature.geometry.coordinates);
      }
    });

    // Apply a robust padding of 8% to prevent clipping at the borders of zoomed regions
    Object.keys(bounds).forEach((key) => {
      if (key === "All") return;
      const b = bounds[key];
      const w = b.maxX - b.minX;
      const h = b.maxY - b.minY;
      const padX = w * 0.08;
      const padY = h * 0.08;

      bounds[key] = {
        minX: Math.max(0, b.minX - padX),
        maxX: Math.min(canvasWidth, b.maxX + padX),
        minY: Math.max(0, b.minY - padY),
        maxY: Math.min(canvasHeight, b.maxY + padY)
      };
    });

    return {
      features: projectedFeatures,
      bounds,
      canvasWidth,
      canvasHeight
    };
  }, [geoData]);

  // Compute active viewBox with coordinates based on zoom selection
  const activeViewBox = useMemo(() => {
    if (!mapData) return "0 0 1000 1400";
    const b = mapData.bounds[activeRegion];
    if (!b) return "0 0 1000 1400";
    const w = b.maxX - b.minX;
    const h = b.maxY - b.minY;
    return `${b.minX.toFixed(1)} ${b.minY.toFixed(1)} ${w.toFixed(1)} ${h.toFixed(1)}`;
  }, [mapData, activeRegion]);

  // Warning metrics summary
  const warningMetrics = useMemo(() => {
    if (!activeAdvisory || !activeAdvisory.provinces) return { red: 0, orange: 0, yellow: 0, lightBlue: 0, gray: 0, normal: 0 };
    let red = 0, orange = 0, yellow = 0, lightBlue = 0, gray = 0, normal = 0;
    Object.values(activeAdvisory.provinces).forEach((p) => {
      const mm = p.rainfall_mm || 0;
      if (activeThresholds.purple && mm >= activeThresholds.purple) red++;
      else if (mm >= activeThresholds.red) red++;
      else if (mm >= activeThresholds.orange) orange++;
      else if (mm >= activeThresholds.yellow) yellow++;
      else if (mm >= activeThresholds.lightBlue) lightBlue++;
      else if (activeThresholds.gray && mm >= activeThresholds.gray) gray++;
      else normal++;
    });
    return { red, orange, yellow, lightBlue, gray, normal };
  }, [activeAdvisory, activeThresholds]);

  // Warning provinces lists
  const warningProvinces = useMemo(() => {
    const red = [];
    const orange = [];
    const yellow = [];
    const lightBlue = [];
    const gray = [];

    if (activeAdvisory && activeAdvisory.provinces) {
      Object.entries(activeAdvisory.provinces).forEach(([name, p]) => {
        const mm = p.rainfall_mm || 0;
        if (mm >= activeThresholds.red) red.push(name);
        else if (mm >= activeThresholds.orange) orange.push(name);
        else if (mm >= activeThresholds.yellow) yellow.push(name);
        else if (mm >= activeThresholds.lightBlue) lightBlue.push(name);
        else if (activeThresholds.gray && mm >= activeThresholds.gray) gray.push(name);
      });
      red.sort();
      orange.sort();
      yellow.sort();
      lightBlue.sort();
      gray.sort();
    }

    return { red, orange, yellow, lightBlue, gray };
  }, [activeAdvisory, activeThresholds]);

  const handleMouseMove = (e) => {
    if (mapContainerRef.current) {
      const rect = mapContainerRef.current.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;

      // Tooltip dimensions: width is 288px (w-72), estimated height is 210px
      const tooltipWidth = 290;
      const tooltipHeight = 210;

      let finalX = x + 15;
      let finalY = y + 15;

      // Check right boundary collision
      if (x + tooltipWidth > rect.width) {
        finalX = x - tooltipWidth - 15;
      }

      // Check bottom boundary collision
      if (y + tooltipHeight > rect.height) {
        finalY = y - tooltipHeight - 15;
      }

      // Keep within bounds
      finalX = Math.max(10, finalX);
      finalY = Math.max(10, finalY);

      setTooltipPos({
        x: finalX,
        y: finalY,
      });
    }
  };

  const getRainfallColor = (mm) => {
    if (activeThresholds.purple && mm >= activeThresholds.purple) return "#701A75"; // Dark Red / Purple
    if (mm >= activeThresholds.red) return "#DC2626"; // Red (Severe)
    if (mm >= activeThresholds.orange) return "#F97316"; // Orange (Heavy)
    if (mm >= activeThresholds.yellow) return "#EAB308";  // Yellow (Moderate)
    if (mm >= activeThresholds.lightBlue) return "#38BDF8";  // Light Blue (Light-Moderate)
    if (activeThresholds.gray && mm >= activeThresholds.gray) return "#64748B"; // Gray
    return "#334155"; // Default Slate
  };

  const getAlertLevel = (mm) => {
    const units = dataSource === "forecast" ? "mm / 24h" : `mm / ${observedWindow}`;
    
    if (activeThresholds.purple && mm >= activeThresholds.purple) {
      return {
        title: "Extreme Purple Warning",
        style: "bg-fuchsia-950/40 text-fuchsia-300 border-fuchsia-900/40",
        text: `Extreme torrential rainfall of ${formatRainfall(mm)} ${units} observed. High risk of catastrophic flooding & landslides.`
      };
    }
    if (mm >= activeThresholds.red) {
      let title = "Severe Red Warning";
      let text = `Severe flooding and widespread landslides are expected. Seek high shelter immediately.`;
      if (dataSource === "observed") {
        if (observedWindow === "3h") {
          title = "Extreme / Torrential Red Warning";
          text = `Extreme / torrential rainfall of ${formatRainfall(mm)} ${units} observed. Immediate flooding and landslides likely.`;
        } else if (observedWindow === "6h") {
          title = "Extreme Red Warning";
          text = `Extreme rainfall of ${formatRainfall(mm)} ${units} observed. High flood potential and soil slides expected.`;
        }
      }
      return { title, style: "bg-red-500/20 text-red-400 border-red-500/30", text };
    }
    if (mm >= activeThresholds.orange) {
      return {
        title: "Heavy Orange Alert",
        style: "bg-orange-500/20 text-orange-400 border-orange-500/30",
        text: `Heavy rainfall of ${formatRainfall(mm)} ${units} observed. High risk of flooding & soil slides near hills and rivers.`
      };
    }
    if (mm >= activeThresholds.yellow) {
      return {
        title: "Moderate Yellow Advisory",
        style: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
        text: `Moderate rainfall of ${formatRainfall(mm)} ${units} observed. Localized pooling & minor flooding possible.`
      };
    }
    if (mm >= activeThresholds.lightBlue) {
      let title = "Light Blue Alert";
      let text = `Light to moderate rainfall of ${formatRainfall(mm)} ${units} observed. Localized minor ponding & wet roads possible.`;
      if (dataSource === "observed" && observedWindow === "6h") {
        title = "Light Rain Alert";
        text = `Light rain of ${formatRainfall(mm)} ${units} observed. Standard road safety precautions apply.`;
      }
      return { title, style: "bg-sky-500/20 text-sky-400 border-sky-500/30", text };
    }
    if (activeThresholds.gray && mm >= activeThresholds.gray) {
      return {
        title: "Gray Alert",
        style: "bg-slate-800 text-slate-300 border-slate-700/30",
        text: `Trace to light rainfall of ${formatRainfall(mm)} ${units} observed. Low risk of warning condition.`
      };
    }
    return { title: "No Warnings Active", style: "bg-slate-800 text-slate-400 border-slate-700/30", text: `No significant rainfall (${formatRainfall(mm)} ${units}) observed. Normal conditions.` };
  };

  // Weather radar/met loading screen
  if (!geoData || !activeAdvisory) {
    return (
      <div className="flex flex-col items-center justify-center h-[calc(100vh-64px)] w-full bg-slate-950 text-slate-300">
        <div className="relative flex items-center justify-center">
          <div className="absolute w-24 h-24 rounded-full border-2 border-sky-500/25 animate-ping" />
          <div className="absolute w-16 h-16 rounded-full border-2 border-sky-400/40 animate-pulse" />
          <Compass className="w-14 h-14 text-sky-400 animate-spin" style={{ animationDuration: '3s' }} />
        </div>
        <h2 className="mt-8 text-xl font-bold tracking-widest uppercase text-sky-400">Loading Weather Advisories</h2>
        <p className="mt-2 text-xs text-slate-500 font-mono">Loading dynamic province map overlays & weather models...</p>
      </div>
    );
  }

  return (
    <div className="relative h-[calc(100vh-64px)] w-full bg-slate-950 font-sans overflow-hidden flex flex-col md:flex-row">

      {/* ── INTERACTIVE DYNAMIC MAP CONTAINER ── */}
      <div
        ref={mapContainerRef}
        onMouseMove={handleMouseMove}
        className={`relative w-full transition-all duration-500 ease-in-out bg-[#020617] overflow-hidden flex items-center justify-center border-b md:border-b-0 border-slate-800 ${
          isMobileCollapsed ? "h-[calc(100vh-124px)]" : "h-[40vh]"
        } md:h-full md:flex-1`}
      >
        {/* Radar-like background grid lines */}
        <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(ellipse_at_center,rgba(15,23,42,0.6)_0%,rgba(2,6,23,1)_95%)]" />

        {/* Dynamic Zooming SVG Map Canvas */}
        {mapData && (
          <svg
            className="w-auto h-full max-h-full max-w-full aspect-[1000/1400] relative z-10 select-none cursor-crosshair transition-all duration-[1200ms] ease-[cubic-bezier(0.2,0.8,0.2,1)]"
            viewBox={activeViewBox}
            style={{
              filter: "drop-shadow(0 25px 50px rgba(0, 0, 0, 0.4))",
            }}
            onClick={() => {
              setHoveredProvince(null);
              setIsTooltipVisible(false);
            }}
          >
            {/* Fine Technical Grid Lines */}
            <defs>
              <pattern id="grid" width="100" height="100" patternUnits="userSpaceOnUse">
                <path d="M 100 0 L 0 0 0 100" fill="none" stroke="rgba(51, 65, 85, 0.15)" strokeWidth="0.8" />
              </pattern>
            </defs>
            <rect width={mapData.canvasWidth} height={mapData.canvasHeight} fill="url(#grid)" />

            {/* Latitude/Longitude tick labels */}
            <g opacity="0.15" className="text-[11px] font-mono fill-slate-500">
              <text x="10" y="20">18.5°N</text>
              <text x="10" y="470">15.0°N</text>
              <text x="10" y="930">10.0°N</text>
              <text x="10" y="1380">5.5°N</text>
              <text x="920" y="1390" textAnchor="end">126.5°E</text>
              <text x="470" y="1390" textAnchor="end">121.5°E</text>
              <text x="50" y="1390" textAnchor="end">117.0°E</text>
            </g>

            {/* Vintage meteorological compass rose */}
            <g transform="translate(90, 135)" className="opacity-[0.25] pointer-events-none font-mono">
              <circle r="48" fill="none" stroke="rgba(255,255,255,0.2)" strokeWidth="1" />
              <circle r="40" fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="0.8" strokeDasharray="2 3" />
              <line x1="0" y1="-55" x2="0" y2="55" stroke="rgba(255,255,255,0.25)" strokeWidth="0.8" />
              <line x1="-55" y1="0" x2="55" y2="0" stroke="rgba(255,255,255,0.25)" strokeWidth="0.8" />

              {/* North Arrow Pointer */}
              <polygon points="0,-52 4,-12 0,0 -4,-12" fill="rgba(255,255,255,0.4)" />
              <polygon points="0,52 3,12 0,0 -3,12" fill="rgba(255,255,255,0.15)" />
              <polygon points="52,0 12,3 0,0 12,-3" fill="rgba(255,255,255,0.15)" />
              <polygon points="-52,0 -12,3 0,0 -12,-3" fill="rgba(255,255,255,0.15)" />

              <text x="0" y="-60" textAnchor="middle" fill="rgba(255,255,255,0.6)" fontSize="10" fontWeight="bold">N</text>
              <text x="64" y="3" textAnchor="middle" fill="rgba(255,255,255,0.4)" fontSize="8">E</text>
              <text x="0" y="69" textAnchor="middle" fill="rgba(255,255,255,0.4)" fontSize="8">S</text>
              <text x="-64" y="3" textAnchor="middle" fill="rgba(255,255,255,0.4)" fontSize="8">W</text>
            </g>

            {/* Render all 82 Province Paths dynamically */}
            <g>
              {mapData.features.map((feature) => {
                const rainfall = activeAdvisory.provinces[feature.name]?.rainfall_mm || 0;
                const isHovered = hoveredProvince?.id === feature.id;
                const fill = getRainfallColor(rainfall);

                return (
                  <path
                    key={feature.id}
                    d={feature.d}
                    fill={fill}
                    stroke={isHovered ? "#ffffff" : "rgba(15, 23, 42, 0.4)"}
                    strokeWidth={isHovered ? 2.5 : 0.8}
                    strokeLinejoin="round"
                    className="transition-all duration-300 cursor-pointer"
                    style={{
                      opacity: hoveredProvince && !isHovered ? 0.35 : 1,
                      filter: isHovered ? "drop-shadow(0 0 8px rgba(255,255,255,0.4)) brightness(1.15)" : "none"
                    }}
                    onMouseEnter={() => {
                      setHoveredProvince({
                        ...feature,
                        rainfall,
                        alert: getAlertLevel(rainfall)
                      });
                      setIsTooltipVisible(true);
                    }}
                    onMouseLeave={() => {
                      setHoveredProvince(null);
                      setIsTooltipVisible(false);
                    }}
                    onClick={(e) => {
                      e.stopPropagation();
                      const currentProv = {
                        ...feature,
                        rainfall,
                        alert: getAlertLevel(rainfall)
                      };
                      if (hoveredProvince?.id === feature.id) {
                        setHoveredProvince(null);
                        setIsTooltipVisible(false);
                      } else {
                        setHoveredProvince(currentProv);
                        setIsTooltipVisible(true);
                      }
                    }}
                  />
                );
              })}
            </g>

            {/* Interactive Province Labels (Optionally toggled, or defaults to centroid markers) */}
            <g className="pointer-events-none select-none font-mono">
              {mapData.features.map((feature) => {
                const rainfall = activeAdvisory.provinces[feature.name]?.rainfall_mm || 0;
                const isHovered = hoveredProvince?.id === feature.id;

                // Only render small high-importance visual guides or toggled text
                if (showLabels && feature.centroid && (rainfall >= 50 || isHovered)) {
                  return (
                    <g key={`lbl-${feature.id}`} transform={`translate(${feature.centroid[0]}, ${feature.centroid[1]})`}>
                      {/* High-visibility label backdrop */}
                      <rect
                        x={-(feature.name.length * 3.2 + 6)}
                        y="-15"
                        width={feature.name.length * 6.4 + 12}
                        height="18"
                        rx="4"
                        fill="rgba(15, 23, 42, 0.85)"
                        stroke="rgba(255,255,255,0.15)"
                        strokeWidth="0.5"
                      />
                      <text
                        y="-3"
                        textAnchor="middle"
                        fill={isHovered ? "#ffffff" : "#cbd5e1"}
                        fontSize="8.5"
                        fontWeight={rainfall >= 100 ? "bold" : "normal"}
                      >
                        {feature.name}
                      </text>
                    </g>
                  );
                }
                return null;
              })}
            </g>
          </svg>
        )}

        {/* Floating Controller overlay */}
        <div className="absolute top-4 left-4 right-4 z-20 flex flex-row md:flex-col items-center md:items-start gap-2.5 flex-wrap pointer-events-none">
          {/* Island Group Selector */}
          <div className="bg-slate-950/80 backdrop-blur-md p-1 rounded-lg border border-slate-800/80 shadow-xl flex gap-1 pointer-events-auto">
            {["All", "Luzon", "Visayas", "Mindanao"].map((region) => (
              <button
                key={region}
                onClick={() => setActiveRegion(region)}
                className={`px-2.5 py-1 rounded-md text-[10px] sm:text-xs font-bold tracking-wide uppercase cursor-pointer transition-all duration-300 ${activeRegion === region
                  ? "bg-sky-500 text-white shadow-md shadow-sky-500/10 scale-105"
                  : "text-slate-400 hover:text-slate-200 hover:bg-slate-900/50"
                  }`}
              >
                {region}
              </button>
            ))}
          </div>

          {/* Toggle Map Labels Label overlay */}
          <button
            onClick={() => setShowLabels(!showLabels)}
            className={`px-2.5 py-1.5 rounded-lg text-[10px] sm:text-xs font-semibold backdrop-blur-md border shadow-lg flex items-center justify-center gap-1.5 pointer-events-auto cursor-pointer transition-all duration-300 ${showLabels
              ? "bg-emerald-600/80 text-white border-emerald-500"
              : "bg-slate-950/80 text-slate-400 border-slate-800 hover:bg-slate-900/80"
              }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>{showLabels ? "Hide Names" : "Show Names"}</span>
          </button>

          {/* Export PNG Button */}
          <button
            onClick={exportMapAsPNG}
            className="px-2.5 py-1.5 rounded-lg text-[10px] sm:text-xs font-semibold backdrop-blur-md border shadow-lg flex items-center justify-center gap-1.5 pointer-events-auto cursor-pointer bg-slate-950/80 text-slate-400 border-slate-800 hover:bg-slate-900/80 hover:text-sky-400 transition-all duration-300"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export PNG</span>
          </button>
        </div>

        {/* ── DYNAMIC CURSOR FLOATING GLASS TOOLTIP (DESKTOP ONLY) ── */}
        {isTooltipVisible && hoveredProvince && (
          <div
            className="hidden md:flex absolute z-50 pointer-events-none w-72 rounded-xl border border-slate-700/60 bg-slate-950/90 p-4 text-slate-200 shadow-2xl backdrop-blur-lg transition-opacity duration-200 flex flex-col gap-2.5"
            style={{
              left: tooltipPos.x,
              top: tooltipPos.y,
              transform: "translate3d(0, 0, 0)"
            }}
          >
            {/* Tooltip Header */}
            <div className="flex justify-between items-start border-b border-slate-800 pb-2">
              <div>
                <h3 className="font-bold text-slate-100 text-sm tracking-wide">{hoveredProvince.name}</h3>
                <p className="text-[10px] font-semibold text-sky-400 uppercase tracking-wider mt-0.5">
                  {hoveredProvince.group} • {hoveredProvince.region.split("(")[0].trim()}
                </p>
              </div>
              <MapPin className="w-4 h-4 text-sky-400 opacity-80" />
            </div>

            {/* Precipitation reading metrics */}
            <div className="flex items-center gap-4 bg-slate-900/60 px-3 py-2 rounded-lg border border-slate-800">
              <div className="flex items-center justify-center w-8 h-8 rounded-full bg-sky-500/10 text-sky-400">
                <CloudRain className="w-4 h-4 animate-pulse" />
              </div>
              <div>
                <p className="text-[10px] text-slate-500 font-mono uppercase tracking-wider">
                  {dataSource === "forecast" ? "Forecast Rainfall" : "Observed Rainfall"}
                </p>
                <p className="text-base font-bold text-white tracking-wide">
                  {formatRainfall(hoveredProvince.rainfall)} <span className="text-xs font-normal text-slate-400">mm / {dataSource === "forecast" ? "24h" : observedWindow}</span>
                </p>
              </div>
            </div>

            {/* Custom localized advisory actions */}
            <div className={`p-2.5 rounded-lg border text-xs leading-relaxed flex flex-col gap-1 ${hoveredProvince.alert.style}`}>
              <div className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-[10px]">
                <ShieldAlert className="w-3.5 h-3.5" />
                <span>{hoveredProvince.alert.title}</span>
              </div>
              <p className="opacity-90">{hoveredProvince.alert.text}</p>
            </div>
          </div>
        )}

        {/* ── MOBILE SLIDE-UP GLASS BOTTOM-SHEET PANEL ── */}
        {hoveredProvince && (
          <div className="absolute bottom-4 left-4 right-4 z-30 md:hidden pointer-events-auto rounded-xl border border-slate-700/60 bg-slate-950/95 p-3.5 shadow-2xl backdrop-blur-lg flex flex-col gap-2.5 animate-in fade-in slide-in-from-bottom-5 duration-300">
            <div className="flex justify-between items-start">
              <div>
                <h3 className="font-bold text-slate-100 text-sm tracking-wide">{hoveredProvince.name}</h3>
                <p className="text-[10px] font-semibold text-sky-400 uppercase tracking-wider mt-0.5">
                  {hoveredProvince.group} • {hoveredProvince.region.split("(")[0].trim()}
                </p>
              </div>
              <MapPin className="w-4 h-4 text-sky-400 opacity-80" />
            </div>

            <div className="flex items-center justify-between gap-4 bg-slate-900/60 px-3 py-1.5 rounded-lg border border-slate-800">
              <div className="flex items-center gap-2">
                <CloudRain className="w-3.5 h-3.5 text-sky-400 animate-pulse" />
                <span className="text-[10px] text-slate-400 uppercase tracking-wider font-mono">Rainfall:</span>
              </div>
              <p className="text-sm font-bold text-white tracking-wide">
                {formatRainfall(hoveredProvince.rainfall)} <span className="text-[10px] font-normal text-slate-400">mm / {dataSource === "forecast" ? "24h" : observedWindow}</span>
              </p>
            </div>

            <div className={`p-2 rounded-lg border text-[11px] leading-snug flex items-center gap-2 ${hoveredProvince.alert.style}`}>
              <ShieldAlert className="w-4 h-4 flex-shrink-0" />
              <p className="opacity-95">{hoveredProvince.alert.text}</p>
            </div>
          </div>
        )}

      </div>

      {/* ── SIDEBAR PANEL (PAGASA WEATHER ALERT DESK STYLE) ── */}
      <div
        className={`w-full md:w-80 lg:w-96 transition-all duration-500 ease-in-out bg-[#090d16]/95 md:bg-[#050811]/90 backdrop-blur-xl border-t md:border-t-0 md:border-l border-slate-800/80 flex flex-col z-20 overflow-hidden shadow-[-15px_0_35px_rgba(0,0,0,0.6)] ${
          isMobileCollapsed ? "h-[60px]" : "h-[calc(60vh-64px)]"
        } md:h-full flex-1 md:flex-none`}
      >

        {/* PAGASA Style Header */}
        <div
          onClick={() => {
            if (window.innerWidth < 768) {
              setIsMobileCollapsed(!isMobileCollapsed);
            }
          }}
          className={`bg-gradient-to-r from-sky-950/80 to-blue-950/80 px-5 border-b border-sky-800/40 text-center relative overflow-hidden flex-shrink-0 cursor-pointer md:cursor-default transition-all duration-300 ${
            isMobileCollapsed ? "py-4" : "py-5"
          }`}
        >
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(14,165,233,0.1)_0%,transparent_70%)] pointer-events-none" />
          <h1 className="text-sm sm:text-base md:text-lg font-black tracking-widest text-white uppercase flex items-center justify-center gap-2 relative">
            <ShieldAlert className="w-4 h-4 md:w-5 md:h-5 text-sky-400" />
            <span>{dataSource === "forecast" ? "Rainfall Forecast" : "Observed Rainfall"}</span>
            <span className="absolute right-0 top-1/2 -translate-y-1/2 md:hidden">
              {isMobileCollapsed ? (
                <ChevronUp className="w-5 h-5 text-sky-400 animate-bounce" />
              ) : (
                <ChevronDown className="w-5 h-5 text-slate-400" />
              )}
            </span>
          </h1>
          <p className={`text-[10px] md:text-xs font-semibold text-sky-300 uppercase tracking-widest mt-1 transition-all duration-300 ${
            isMobileCollapsed ? "hidden md:block" : "block"
          }`}>
            {dataSource === "forecast" ? "24-Hour Advisory Bulletin" : "24-Hour Observation Bulletin"}
          </p>
          {activeAdvisory && (
            <div className={`mt-3 flex flex-col gap-1.5 items-center transition-all duration-300 ${
              isMobileCollapsed ? "hidden md:flex" : "flex"
            }`}>
              <span className="text-[10px] text-slate-300 font-mono bg-slate-950/70 py-1 px-3 rounded-full border border-slate-800/60 w-fit">
                {activeAdvisory.validity}
              </span>
              <span className="text-[9px] text-slate-400 font-mono uppercase tracking-wider">
                {dataSource === "forecast" ? "Model Run:" : "Obs Window:"} {activeAdvisory.init_time}
              </span>
            </div>
          )}
        </div>

        {/* Model Forecast Context Card */}
        <div className="p-4 bg-slate-950/50 border-b border-slate-900 flex flex-col gap-3.5 flex-shrink-0">
          {/* Toggle Segmented Control */}
          <div className="bg-slate-900/80 p-1 rounded-lg border border-slate-800 flex gap-1 w-full pointer-events-auto">
            <button
              onClick={() => setDataSource("forecast")}
              className={`flex-1 py-1.5 rounded-md text-[10px] sm:text-xs font-bold tracking-wide uppercase cursor-pointer transition-all duration-305 ${
                dataSource === "forecast"
                  ? "bg-sky-500 text-white shadow-md shadow-sky-500/10 scale-105"
                  : "text-slate-400 hover:text-slate-200 hover:bg-slate-900/50"
              }`}
            >
              Forecast
            </button>
            <button
              onClick={() => setDataSource("observed")}
              className={`flex-1 py-1.5 rounded-md text-[10px] sm:text-xs font-bold tracking-wide uppercase cursor-pointer transition-all duration-305 ${
                dataSource === "observed"
                  ? "bg-sky-500 text-white shadow-md shadow-sky-500/10 scale-105"
                  : "text-slate-400 hover:text-slate-200 hover:bg-slate-900/50"
              }`}
            >
              Observed
            </button>
          </div>

          {/* Observed Time Window Selector (Only visible when Observed is active) */}
          {dataSource === "observed" && (
            <div className="flex flex-col gap-1.5 animate-in fade-in slide-in-from-top-1 duration-200">
              <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">Observation Window:</span>
              <div className="bg-slate-900/80 p-1 rounded-lg border border-slate-800 flex gap-0.5 w-full pointer-events-auto">
                {["1h", "3h", "6h", "12h", "24h"].map((windowOpt) => (
                  <button
                    key={windowOpt}
                    onClick={() => setObservedWindow(windowOpt)}
                    className={`flex-1 py-1 rounded text-[10px] font-bold uppercase cursor-pointer transition-all duration-200 ${
                      observedWindow === windowOpt
                        ? "bg-emerald-500 text-white shadow-sm"
                        : "text-slate-400 hover:text-slate-200 hover:bg-slate-800/30"
                    }`}
                  >
                    {windowOpt}
                  </button>
                ))}
              </div>
            </div>
          )}

          <div>
            <div className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">
              {dataSource === "forecast" ? "Forecast Model:" : "Observation Source:"}
            </div>
            <div className="text-sm font-bold text-sky-400 mt-0.5">{activeAdvisory.system}</div>
          </div>
        </div>

        {/* Advisory Action Tables */}
        <div className="p-5 flex-1 overflow-y-auto space-y-5">

          <h2 className="text-slate-400 font-bold uppercase tracking-wider text-[11px] flex items-center gap-1.5 border-b border-slate-800/80 pb-2 mb-4">
            <TrendingUp className="w-3.5 h-3.5 text-sky-400" />
            <span>Threat Warning Categories</span>
          </h2>

          {/* Red Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-red-950 shadow-lg group transition-all duration-300 hover:border-red-900/60">
            <div className="bg-gradient-to-r from-red-700 to-red-600 px-4 py-2 flex justify-between items-center text-white text-xs font-bold tracking-widest uppercase">
              <span>{dataSource === "observed" && observedWindow === "1h" ? "Red / Purple Level (20+ mm)" : `Red Level (${activeThresholds.red}+ mm)`}</span>
              {warningMetrics.red > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-slate-950 text-[10px] text-red-400 border border-red-500/35 font-bold shadow-md animate-pulse">
                  {warningMetrics.red} Provinces
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              {getLevelMeaning("red", observedWindow, dataSource === "observed") && (
                <div className="text-[10.5px] font-semibold text-red-300 bg-red-950/40 px-2 py-1 rounded border border-red-900/40 w-fit mb-3">
                  {getLevelMeaning("red", observedWindow, dataSource === "observed")}
                </div>
              )}
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-red-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Extreme, catastrophic flooding expected in highly vulnerable areas and low plains.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-red-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Landslides:</strong> Extreme, widespread landslides are highly likely in high-slope mountain zones.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-red-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Evacuate hazard-exposed residences. Seek high shelter immediately.</p>
              </div>

              {/* Affected Provinces Name List */}
              {warningProvinces.red.length > 0 && (
                <div className="pt-3 mt-3 border-t border-slate-900/60">
                  <span className="text-[9.5px] font-bold text-red-400 uppercase tracking-wider block mb-1.5 text-left">Affected Provinces:</span>
                  <div className="flex flex-wrap gap-1 justify-start">
                    {warningProvinces.red.map(p => {
                      const mm = activeAdvisory.provinces[p]?.rainfall_mm || 0;
                      const isPurple = activeThresholds.purple && mm >= activeThresholds.purple;
                      return (
                        <span
                          key={p}
                          className={`px-1.5 py-0.5 border rounded text-[9.5px] font-mono ${
                            isPurple
                              ? "bg-fuchsia-950/60 text-fuchsia-300 border-fuchsia-900/60"
                              : "bg-red-950/60 text-red-300 border-red-900/60"
                          }`}
                        >
                          {p} ({formatRainfall(mm)}mm)
                        </span>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Orange Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-orange-950 shadow-lg group transition-all duration-300 hover:border-orange-900/60">
            <div className="bg-gradient-to-r from-orange-600 to-orange-500 px-4 py-2 flex justify-between items-center text-white text-xs font-bold tracking-widest uppercase">
              <span>Orange Level ({activeThresholds.orange}-{activeThresholds.red} mm)</span>
              {warningMetrics.orange > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-slate-950 text-[10px] text-orange-400 border border-orange-500/35 font-bold shadow-md">
                  {warningMetrics.orange} Provinces
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-orange-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Severe widespread urban and lowland flooding near water channels.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-orange-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Landslides:</strong> Heavy soil saturations likely to cause slides in moderate risk mountains.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-orange-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Prepare grab-bags and emergency supplies. Be on standby alert to evacuate.</p>
              </div>

              {/* Affected Provinces Name List */}
              {warningProvinces.orange.length > 0 && (
                <div className="pt-3 mt-3 border-t border-slate-900/60">
                  <span className="text-[9.5px] font-bold text-orange-400 uppercase tracking-wider block mb-1.5 text-left">Affected Provinces:</span>
                  <div className="flex flex-wrap gap-1 justify-start">
                    {warningProvinces.orange.map(p => (
                      <span key={p} className="px-1.5 py-0.5 bg-orange-950/60 text-orange-300 border border-orange-900/60 rounded text-[9.5px] font-mono">
                        {p} ({formatRainfall(activeAdvisory.provinces[p]?.rainfall_mm || 0)}mm)
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Yellow Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-yellow-950 shadow-lg group transition-all duration-300 hover:border-yellow-900/60">
            <div className="bg-gradient-to-r from-yellow-500 to-yellow-400 px-4 py-2 flex justify-between items-center text-slate-900 text-xs font-extrabold tracking-widest uppercase">
              <span>Yellow Level ({activeThresholds.yellow}-{activeThresholds.orange} mm)</span>
              {warningMetrics.yellow > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-slate-950 text-[10px] text-yellow-400 border border-yellow-500/35 font-bold shadow-md">
                  {warningMetrics.yellow} Provinces
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Light localized pooling in highly urbanized street sectors.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Landslides:</strong> Isolated, small mud slips possible near mountain cuts.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Stay tuned to warnings. Clear yard debris and monitor channel flows.</p>
              </div>

              {/* Affected Provinces Name List */}
              {warningProvinces.yellow.length > 0 && (
                <div className="pt-3 mt-3 border-t border-slate-900/60">
                  <span className="text-[9.5px] font-bold text-yellow-400 uppercase tracking-wider block mb-1.5 text-left">Affected Provinces:</span>
                  <div className="flex flex-wrap gap-1 justify-start">
                    {warningProvinces.yellow.map(p => (
                      <span key={p} className="px-1.5 py-0.5 bg-yellow-950/50 text-yellow-300 border border-yellow-900/40 rounded text-[9.5px] font-mono">
                        {p} ({formatRainfall(activeAdvisory.provinces[p]?.rainfall_mm || 0)}mm)
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Light Blue Level */}
          <div className="bg-slate-950/40 rounded-xl overflow-hidden border border-sky-950 shadow-lg group transition-all duration-300 hover:border-sky-900/60">
            <div className="bg-gradient-to-r from-sky-600 to-sky-500 px-4 py-2 flex justify-between items-center text-white text-xs font-bold tracking-widest uppercase">
              <span>Light Blue Level ({activeThresholds.lightBlue === 0.1 ? "0.1" : activeThresholds.lightBlue}-{activeThresholds.yellow} mm)</span>
              {warningMetrics.lightBlue > 0 && (
                <span className="px-1.5 py-0.5 rounded-full bg-slate-950 text-[10px] text-sky-400 border border-sky-500/35 font-bold shadow-md">
                  {warningMetrics.lightBlue} Provinces
                </span>
              )}
            </div>
            <div className="p-4 text-xs text-slate-400 leading-relaxed space-y-2">
              {getLevelMeaning("lightBlue", observedWindow, dataSource === "observed") && (
                <div className="text-[10.5px] font-semibold text-sky-300 bg-sky-950/40 px-2 py-1 rounded border border-sky-900/40 w-fit mb-3">
                  {getLevelMeaning("lightBlue", observedWindow, dataSource === "observed")}
                </div>
              )}
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-sky-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Flooding:</strong> Low localized ponding on streets and urban low points.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-sky-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Landslides:</strong> Very low risk. Minor cut bank precautions.</p>
              </div>
              <div className="flex items-start gap-2">
                <ChevronRight className="w-3 h-3 text-sky-500 mt-0.5 flex-shrink-0" />
                <p><strong className="text-slate-200">Action:</strong> Stay alert, monitor weather updates, and observe standard road safety rules.</p>
              </div>

              {/* Affected Provinces Name List */}
              {warningProvinces.lightBlue.length > 0 && (
                <div className="pt-3 mt-3 border-t border-slate-900/60">
                  <span className="text-[9.5px] font-bold text-sky-400 uppercase tracking-wider block mb-1.5 text-left">Affected Provinces:</span>
                  <div className="flex flex-wrap gap-1 justify-start">
                    {warningProvinces.lightBlue.map(p => (
                      <span key={p} className="px-1.5 py-0.5 bg-sky-950/60 text-sky-300 border border-sky-900/60 rounded text-[9.5px] font-mono">
                        {p} ({formatRainfall(activeAdvisory.provinces[p]?.rainfall_mm || 0)}mm)
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>


        </div>

        {/* Meteorological Footer info */}
        {activeAdvisory && (
          <div className="bg-slate-950 p-4 border-t border-slate-900 flex flex-col gap-2 relative flex-shrink-0">
            <div className="text-emerald-400 font-bold text-xs text-center tracking-wide uppercase">
              {activeAdvisory.title}
            </div>
            <div className="flex items-center justify-center gap-3 mt-1 pb-1">
              <img src="/images/logo.png" alt="Logo" className="h-7 w-7 opacity-85 object-contain" />
              <div className="text-[9px] text-slate-500 font-mono leading-tight">
                {activeAdvisory.system}<br />
                Weather Analysis & Forecasting Desk
              </div>
            </div>
          </div>
        )}

      </div>

      {/* ── RESPONSIVE MOBILE DISPLAY ADVISORY MODAL ── */}
      {showMobileNotice && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center p-5 bg-slate-950/80 backdrop-blur-lg animate-in fade-in duration-300">
          <div className="relative max-w-md w-full bg-[#080d19]/95 border border-slate-800/80 rounded-2xl p-6 text-center shadow-2xl flex flex-col items-center gap-5 animate-in zoom-in-95 duration-300">
            {/* Glowing Smartphone Alert Icon */}
            <div className="relative flex items-center justify-center w-16 h-16 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20">
              <Smartphone className="w-8 h-8" />
              <span className="absolute inset-0 rounded-full border border-amber-500/30 animate-ping" style={{ animationDuration: '2s' }} />
            </div>

            {/* Warning Message Content */}
            <div className="space-y-2">
              <h2 className="text-lg font-extrabold tracking-wide text-slate-100 uppercase">Screen Size Notice</h2>
              <p className="text-xs text-slate-400 leading-relaxed pt-1.5 font-semibold text-amber-300">
                This page is not optimized for small screens.
              </p>
              <p className="text-xs text-slate-400 leading-relaxed">
                You can still access this page but it may not perform well; we suggest that you go to a desktop site.
              </p>
              <p className="text-[11px] font-bold text-sky-400 pt-1 font-mono">
                Thank you for your understanding!
              </p>
            </div>

            {/* OK Got It Action Button */}
            <button
              onClick={() => {
                setShowMobileNotice(false);
                if (typeof window !== "undefined") {
                  const todayStr = new Date().toISOString().split('T')[0];
                  localStorage.setItem("ph_weather_mobile_notice_dismissed_date", todayStr);
                }
              }}
              className="w-full mt-2 py-3 rounded-xl bg-sky-500 hover:bg-sky-600 active:scale-[0.98] text-white text-xs font-bold uppercase tracking-wider shadow-lg shadow-sky-500/25 transition-all duration-200 pointer-events-auto cursor-pointer"
            >
              Understand & Proceed
            </button>
          </div>
        </div>
      )}

    </div>
  );
};

export default WeatherAdvisory;
